### ISSUE TITLE
Move single-project/multi-module-project integration tests off bintray and checkstyle.xml

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite-maven-plugin#101]
as in, https://github.com/openrewrite/rewrite-maven-plugin/blob/95e09b28f8a523b92ee1bd0313812d30b1d4a4ea/src/it/single-project/pom.xml#L23-L34

just something I noticed, not solving it at this exact second. adding for backlogging.

**Comment by sambsnyd** [comment]
The defunct repository references cause no harm. I agree they should be removed.
