### ISSUE TITLE
Investigate a better solution to running the maven plugin from a multi-module project.

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-maven-plugin#103]
Currently, if you add the rewrite maven plugin to the top-level pom of a multi-module project, the following error is encountered if you run `mvn rewrite:fix` from the top level:

```
[ERROR] No plugin found for prefix 'org.openrewrite.maven.rewrite' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories
```

Running the same command from the sub-modules works ok. 

A workaround for this issue is to add the following to your maven settings file `~/.m2/settings.xml`

```
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
      <pluginGroups>
        <pluginGroup>org.openrewrite.maven</pluginGroup>
      </pluginGroups>
    </settings>
```

The error provides this link and we should investigate a better solution.
https://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by aegershman** [comment]
Notes:

- Using https://github.com/spring-cloud/spring-cloud-config we can reproduce this
- Just for fun, we can force success using the fully-qualified name: `./mvnw org.openrewrite.maven:rewrite-maven-plugin:discover` (or run, dryRun, etc. would all work)
- more notes tbd, will edit this comment

**Comment by aegershman** [comment]
Closing for the time being. After troubleshooting and reading, I don't believe this is fundamentally an issue with how we have the rewrite-maven-plugin structured or metadata publishing 👍  Included hint about it in the docs just for reference to help folks who might run into it and how one might get unstuck if that were to happen. But I don't believe it's an issue with the plugin, I believe it's something contingent on how the pom.xml is set up.
