### ISSUE TITLE
Update maven goal names, leave behind old names as undocumented aliases for now

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite-maven-plugin#110]
"warn" and "fix" are legacy names from when we thought quite a bit differently about the intended usage of these things. 
"rewrite:fix" should be renamed to "rewrite:run".
"rewrite:warn" should be renamed to "rewrite:dryrun". The existing behavior only prints which files would be changed by which visitors, which isn't very useful. It should instead print what the actual changes would be, similar to what git diff would show you after running run/fix

**Comment by aegershman** [comment]
- renaming closed in https://github.com/openrewrite/rewrite-maven-plugin/pull/115
- changing of behavior documented in separate issue of https://github.com/openrewrite/rewrite-maven-plugin/issues/116
