### ISSUE TITLE
rewrite:dryRun should default to showing what the actual changes would be, similar to git diff

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite-maven-plugin#116]
from https://github.com/openrewrite/rewrite-maven-plugin/issues/110 to keep separate

>"rewrite:warn" should be renamed to "rewrite:dryrun". The existing behavior only prints which files would be changed by which visitors, which isn't very useful. It should instead print what the actual changes would be, similar to what git diff would show you after running run/fix

**Comment by okundzich** [comment]
https://github.com/openrewrite/rewrite-gradle-plugin/issues/27#issuecomment-815159603 Please consider this here as well.
