### ISSUE TITLE
Alternative `PomCache` directories

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite-maven-plugin#122]
for consideration:

In order to prevent parallel maven executions from colliding with one another trying to acquire the global rocksdb lockfile when multiple separate maven processes run, consider PomCache resolution alternatives, such as--

- cache at a project-specific level, e.g. in the `target/` folder
- in-memory caching
- don't explode if the lockfile is held by another process

**Comment by sambsnyd** [comment]
We addressed this at some point... not going to bother digging up the exact issue this is a dupe of right now
