### ISSUE TITLE
Fail when `configLocation` is explicitly defined but not found

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite-maven-plugin#124]
In order to prevent unintended misconfiguration, consider throwing an error if the `configLocation` is explicitly defined but a `rewrite.yml` (or however the user has it named) file does not exist.

To be specific: if the configLocation is not explicitly defined, and a rewrite.yml does not exist in the default directory, the plugin should continue on as normal. It's only if the location is explicitly defined and the file does not exist that there should be an issue.

Just for consideration of usability enhancement.

**Comment by jkschneider** [comment]
The intention here was to permit an organization-wide standard shipped through a parent POM, whereby not all child POMs will define their own recipes in a `rewrite.yml`. Not sure how to reconcile these two. Even a log message would be extraneous in this case.
