### ISSUE TITLE
Ignore recipes that cannot be parsed

### ISSUE THREAD

**Issue by okundzich** [openrewrite/rewrite-maven-plugin#159]
If yaml files containing recipes are not correctly formatted, have missing options, required fields, descriptions, etc, these recipes should be ignored in general.  This is for the use case when someone publishes a bad recipe by mistake, so it doesn't prevent the rest of rewrite from functioning. Since we are looking for recipes on the class path, we can find all sorts of misconfigurations.

Build plugins would need an option/way to describe what is wrong with a specific recipe. This is for the use case when a person is creating a new recipe, and it doesn't activate (it's not found per above), need some way to find out what is wrong with it. For example, discover task with a recipe name will print what is wrong with it (missing description, missing require option, invalid option value etc.) Whatever user experience is most appropriate for these plugins.

**Comment by jkschneider** [comment]
Moved to this project from https://github.com/openrewrite/rewrite, because rewrite core has done enough. Now we need to change the default behavior of the build tool plugins to not fill log output with errors when invalid recipes are encountered.

**Comment by aegershman** [comment]
@okundzich is this taken care of by #161 ? -- for any `activeRecipe`, by default, we log the invalid recipe's validation failures to `[ERROR]`, and ignore it by continuing to process.

If you want to _fail_ when encountering any invalid `activeRecipe`, you can set `failOnInvalidActiveRecipes = true`.

This is only on `activeRecipes`, so it doesn't blow up the logs. We don't do this with _all_ "available" recipes, only the ones that a user has provided to `activeRecipe`.
