### ISSUE TITLE
Show exceptions in log

### ISSUE THREAD

**Issue by pfund** [openrewrite/rewrite-maven-plugin#191]
Hello,

I ran into an openrewrite bug since version 7.8.1 (plugin 4.6.2) and don't see any exception in the console. I only notice that my file is not changed. When running the plugin in debug mode, I see the NullPointerException in the logs. The bug has been fixed but the new version is not out yet (https://github.com/openrewrite/rewrite/issues/744)

**Could it be possible to see the exceptions without debug mode?**

I attached an example project with the bug. When running it with mvn -X rewrite:run you will see the NullPointerException and the file RewriteKO.java is not modified as expected. When running without the -X, you see nothing.

Thanks,

Thomas

[lombokRewrite.zip](https://github.com/openrewrite/rewrite-maven-plugin/files/6792318/lombokRewrite.zip)

**Comment by sambsnyd** [comment]
Hi @pfund, thanks for trying out rewrite and taking the time to report this issue.

All errors during recipe execution _should_ be forwarded to `ExecutionContext.getOnError()`, which in the maven plugin will forward at least the exception's message to the "warn" log level and the full stacktrace to the "debug" log level. You found a situation where that isn't happening and an exception handler in maven itself ends up catching the exception.

After experimenting with trying to smuggle exceptions past our error handling I wasn't able to reproduce this behavior on latest rewrite builds. So hopefully in the next release errors like the one you found wont be hidden.

I will also note that, although we love Lombok, we don't fully support it. Like Rewrite, Lombok is also an AST manipulation tool. If we feed in the Lombok-transformed AST into Rewrite, then the code we'd print back out would include all of the Lombok-generated getters/setters/withers/constructors/etc. If we _don't_ feed the Lombok-transformed AST into Rewrite, then all references to Lombok-generated methods refer to methods that do not exist, potentially confounding refactoring efforts. While this (probably) isn't impossible to resolve in a way that delivers a better user experience, at present your mileage will vary when using Rewrite on Lombok-annotated projects. Generally refactoring recipes that do not interact with lombok-generated methods will still work as intended. But something like `FindMethods` would be unable to find a lombok-generated method.
