### ISSUE TITLE
Warning org.apache.commons:commons-io has been relocated

### ISSUE THREAD

**Issue by Postremus** [openrewrite/rewrite-maven-plugin#223]
When I run recipes on my project using `mvn rewrite:run`, I get following warning from the maven plugin.

The recipes are executed, just an annoying warning.
```
[INFO] --- rewrite-maven-plugin:4.14.0-SNAPSHOT:run (default-cli) @ project ---
[WARNING] The artifact org.apache.commons:commons-io:jar:1.3.2 has been relocated to commons-io:commons-io:jar:1.3.2: https://issues.sonatype.org/browse/MVNCENTRAL-244
```

**Comment by aegershman** [comment]
Merged; right on. I'll go ahead and close this issue, but feel free to @ me if you think it should remain open, or feel free to open any other issues. Thanks again @Postremus good finds, I appreciate it 👍
