### ISSUE TITLE
Document skipMavenParsing option

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite-maven-plugin#238]
The `-DskipMavenParsing` option released in 4.14.0 is not documented on https://docs.openrewrite.org/reference/rewrite-maven-plugin

**Comment by aegershman** [comment]
You're right @murdos thank you. Fixed in https://github.com/openrewrite/rewrite-docs/commit/b89a137a8f93543b626f77c36bb5f7dad2dc89e5

**Comment by delanym** [comment]
Can you clarify what is meant by "skip parsing Maven `pom.xml`s, and any transitive poms, as source files"?

The pom files are necessarily parsed by Maven, and the recipes surely determine their own source files and whether/how they are parsed. I don't get it?

**Comment by xiaowu2012** [comment]
i wanted to understand the impacts if we set this configuration as true. anyone can help on this?
