### ISSUE TITLE
ReplaceJavaxJaxbWithJakarta and ReplaceJavaxJaxwsWithJakarta do not update managed dependencies

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-maven-plugin#243]
Add ManagedDependency updates to ReplaceJavaxJaxbWithJakarta and ReplaceJavaxJaxwsWithJakarta.

**Comment by tkvangorder** [comment]
Closing this issue. The new resolution model should correctly handle managed dependencies. This might be something to revisit as we look closer at the rewrite-migrate-java project.
