### ISSUE TITLE
Add Mojos to add, configure & remove rewrite-maven-plugin

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-maven-plugin#245]
At present the maven plugin mostly assumes the `rewrite-maven-plugin` has already been added to the project `pom.xml`, before any of the goals are usable. I say mostly, because it's also possible to execute the plugin before configuration, by using the full plugin name:

```
./mvnw org.openrewrite.maven:rewrite-maven-plugin:dryRun \
  -DactiveRecipes=org.openrewrite.java.cleanup.CommonStaticAnalysis
```

This opens the door to an easier way to add & configure the Maven Plugin in projects not-yet-configured, at scale.
I imagine it should be possible to add a Mojo such that with one command the plugin is added & configured, or updated.

```
./mvnw org.openrewrite.maven:rewrite-maven-plugin:configure \
  -DactiveRecipes=org.openrewrite.java.spring.boot2.SpringBoot2JUnit4to5Migration \
  -DaddDependency=org.openrewrite.recipe:rewrite-testing-frameworks
```

Notice how such a command has the potential to reduce the Maven documentation from containing XML snippets that users have to apply correctly, to merely showing a plugin command that they have to execute.

If such a configure goal is added, I propose a counter action goal is also added, with which the plugin can be removed, either entirely, or only specific recipes/dependencies.

```
./mvnw org.openrewrite.maven:rewrite-maven-plugin:remove
```

Combining the `configure`, `run` and `remove` goals in this way, could create an easy sequence of commands that users can execute to do single shot project migrations against a large set of projects, without manually having to add and remove the plugin before and after.

Could such goals be added to the Maven plugin?

I briefly dove into the code already, but have limited experience with developing plugins. I imagine you'd want to leverage some of the OpenRewrite recipes themselves if you're to change `pom.xml` files. While I'm not sure I'd be able to complete such a feature, any pointers would also be much appreciated if you're unable/willing to add this to this plugin.

**Comment by aegershman** [comment]
Good thoughts, thanks for writing this up, @timtebeek -- as an aside, it kind of reminds of me of how you can bootstrap adding the maven wrapper to a project by using `mvn -N io.takari:maven:0.7.7:wrapper`. I'll put this in the backlog for the moment, but we'll circle back 👍

**Comment by sambsnyd** [comment]
Thanks for suggesting this, @timtebeek.
I look forward to updating our documentation to provide a convenient, copy + pasteable invocation of the new `init` goal. 

The `init`, `configure`, and `remove` goals I added fill in rewrite-maven-plugin's groupId/artifactId by default, but those can be overridden on the command line. So you can use our plugin to apply, configure, or remove other plugins from the command line, if you are so inclined.

**Comment by timtebeek** [comment]
Awesome to see this added so quickly, thanks! Also nice to repurpose the remove step immediately to also remove other plugins potentially, nice little trick there. :) Can't wait to apply this to projects.

**Comment by timtebeek** [comment]
Tried it just now on an initial Maven project (https://github.com/apache/httpcomponents-client). 

```
mvn org.openrewrite.maven:rewrite-maven-plugin:4.17.0-SNAPSHOT:init \
  -DactiveRecipes=org.openrewrite.java.testing.junit5.ParameterizedRunnerToParameterized \
  -Ddependencies='    <dependencies>
      <dependency>
        <groupId>org.openrewrite.recipe</groupId>
        <artifactId>rewrite-spring</artifactId>
        <version>4.14.1</version>
      </dependency>
      <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-core</artifactId>
        <version>2.13.0</version>
      </dependency>
    </dependencies>'
```

Adding the plugin and dependencies works well; did have to do a local maven install first since there's no release yet.
Was somewhat surprised that to run this one migration I also had to add `jackson-core` as a dependency; is that as intended?

**Comment by timtebeek** [comment]
Also noticed the README has not been updated yet to reflect the new goals, and could do with an example on how to run init given the above example.
