### ISSUE TITLE
Ability to resolve encrypted maven server credentials

### ISSUE THREAD

**Issue by rdifrango** [openrewrite/rewrite-maven-plugin#268]
When I follow the documentation for updating a maven dependency [here](https://docs.openrewrite.org/tutorials/automating-maven-dependency-management), it fails with the following error:
```
cause: org.rocksdb.RocksDBException: While open a file for random read: /Users/my-user-name/.rewrite-cache/000207.ldb: No such file or directory
````

cc: @aegershman

**Comment by aegershman** [comment]
@rdifrango I've implemented decrypting encrypted Maven settings in https://github.com/openrewrite/rewrite-maven-plugin/pull/267 which should be available as a snapshot soon 👀

**Comment by aegershman** [comment]
@rdifrango I'll go ahead and close this. Try this out when you can, and if something doesn't cooperate feel free to log another issue and we'll go from there 👍 Thanks again for logging this

**Comment by rdifrango** [comment]
ok this worked but also discovered another issue so I'll be logging that.
