### ISSUE TITLE
RocksDb caching can persist temporary repository unavailability indefinitely

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite-maven-plugin#273]
To avoid making hopeless requests to repositories that are unavailable, we record when a request to a repository fails and do not attempt further contact with that repository.
But the RocksDb caching layer is persistent, so it can turn a temporary lack of repository availability into a _permanent_ refusal to attempt any request on the repository, at least until the local rewrite pom cache in the user directory is manually deleted.

**Comment by tkvangorder** [comment]
The Pom caching layer has been refactored such that unavailable repositories will be cached in-memory for the life of the maven process. The persistent RocksDb cache will never cache normalized repositories to disk.
