### ISSUE TITLE
Run specific recipe regardless of the configuration in activeRecipes

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-maven-plugin#314]
Is there any way to run specific recipe regardless of what we have configured in `activeRecipes`? 

I tried 

`mvn rewrite:run -DactiveRecipe=org.openrewrite.java.testing.junit5.JUnit4to5Migration
`

But it still ran the rules I have in my configuration. In fact, it ignored the specific recipe and only applied what I have in my configuration

**Comment by pway99** [comment]
Yes, Just pass arguments for both the `rewrite.activeRecipes` and `activeRecipes` params.
Give this a try:
```mvn rewrite:run  -DactiveRecipes="" -Drewrite.activeRecipes=org.openrewrite.java.testing.junit5.JUnit4to5Migration```

**Comment by pway99** [comment]
@yeikel #317 makes this a bit more intuitive:

```
mvn rewrite:run -Drewrite.activeRecipes=org.openrewrite.java.testing.junit5.JUnit4to5Migration
```

**Comment by yeikel** [comment]
> @yeikel #317 makes this a bit more intuitive:
> 
> ```
> mvn rewrite:run -Drewrite.activeRecipes=org.openrewrite.java.testing.junit5.JUnit4to5Migration
> ```

Thank you. I'll try it out as soon as it is released

**Comment by yeikel** [comment]
> > ```
> > mvn rewrite:run -Drewrite.activeRecipes=org.openrewrite.java.testing.junit5.JUnit4to5Migration
> > ```

I was able to confirm that this working as expected now. Thank you @pway99

**Comment by delanym** [comment]
Please remove the incorrect reference in https://docs.openrewrite.org/reference/recipes/java/cleanup/commonstaticanalysis

**Comment by pway99** [comment]
thanks @delanym, I updated the doc.

>Recipes can also be activated directly from the command line by adding the argument
-Drewrite.activeRecipes=org.openrewrite.java.cleanup.CommonStaticAnalysis
