### ISSUE TITLE
No fork goals

### ISSUE THREAD

**Issue by delanym** [openrewrite/rewrite-maven-plugin#331]
Please don't fork the JVM. The modules in my project depend on prior modules reaching the prepare-package phase.
The rewrite-maven-plugin forks the lifecycle and runs to process-test-classes, so whether I run the goal in or out of lifecycle my build fails. You can leave it up to me to prepare the classes.

**Comment by delanym** [comment]
For example of non-forking goals see https://maven.apache.org/plugins/maven-javadoc-plugin/

**Comment by tkvangorder** [comment]
Fixed with 55ea65778ee43126ac8e5761244f73cd7de687b6

@delanym can you test this with the latest snapshot version?

**Comment by delanym** [comment]
@tkvangorder i sure will

**Comment by tkvangorder** [comment]
Hi @delanym , had to do a bit more work. 

We want users to be able to run `rewrite:run` and `rewrite:dryRun` as stand-alone goals, so those will remain. 

However, we added two new variants: `rewrite:runNoFork` and `rewrite:dryRunNoFork` that should address your issue. 

The snapshot version `4.23.0-SNAPSHOT` will include these two new goals.

**Comment by delanym** [comment]
Ok. FYI im getting `java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version 4 (expected 3).` with 4.23.0-SNAPSHOT

**Comment by tkvangorder** [comment]
@delanym Hi, we just upgraded to the new antlr 4.10.x runtime, we may have missed regenerating one of the parsers under the new version. Do you have a stack trace, this would help track down which parser we need to regen?

**Comment by ao-apps** [comment]
We have requested a documentation update for "dryRunNoFork": https://github.com/openrewrite/rewrite-docs/issues/82
