### ISSUE TITLE
Provide a better mechanism for discovering and executing recipes that are available through the build plugins

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-maven-plugin#332]
`mvn rewrite:discover` prints all the recipes available in the class path but it does not run them

Can we add an option to discover and run them as well? An option like `mvn rewrite:discoverAndRun`

From what I understand, if the recipe does not apply to a given class, it runs but terminates quickly

**Comment by tkvangorder** [comment]
I think it would be rare to want to run all recipes, as most of the time a user will be targeting a specific set of actions. However, we do need a better way of discovering and running the available recipes from the plugins.

**Comment by yeikel** [comment]
> I think it would be rare to want to run all recipes, as most of the time a user will be targeting a specific set of actions. However, we do need a better way of discovering and running the available recipes from the plugins.

How about a way to run "all recipes under a package" ?. 

For example, "run all cleanup rules"

**Comment by timtebeek** [comment]
Added a crude first attempt in https://github.com/openrewrite/rewrite-maven-plugin/pull/413 ; any feedback welcome.

**Comment by timtebeek** [comment]
For an interactive experience to discover and run recipes we now recommend folks [use the Moderne CLI](https://docs.moderne.io/user-documentation/getting-started/cli-intro). While we'll retain [the RewriteDiscoverMojo](https://github.com/openrewrite/rewrite-maven-plugin/blob/v5.14.1/src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java) there's no plans to expand that to cover additional search and selection options.
