### ISSUE TITLE
Regarding RocksdbMavenPomCache

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-maven-plugin#336]
In my builds, I get 

`[WARNING] Unable to initialize RocksdbMavenPomCache, falling back to InMemoryMavenPomCache
`

Could you please document how to use this type of cache? 

I could not find any documentation about the same

**Comment by tkvangorder** [comment]
You are right, we have zero documentation on the cache. 

I will try to take a little time to get this on the maven reference docs in gitbook. 

In the meantime: 

Rewrite's maven parser has its own resolution logic for pom files. (It will download metadata and poms from maven repositories). To speed up this process, there is a caching abstraction with two implementations (one that uses rocksdb and one that uses an in-memory cache to reduce the times a pom/metadata should be downloaded from a repository.

The maven plugin uses the rocksdb cache by default and, as you have discovered, if it is unable to instantiate the on-disk database, it will fall back to an in-memory database.

The maven resolution will instantiate the on-disk cache in `~/.rewrite-cache` . The first thing to try would be to delete this folder (if it already exists) and it will be re-created the next time you run the maven build plugin. If the folder does not exist, this may be a file permission issue that is preventing the database from being created.

**Comment by tkvangorder** [comment]
@yeikel I have added a section on the maven pom cache to our docs here: https://docs.openrewrite.org/reference/rewrite-maven-plugin#rewrites-pom-cache

Thanks for reporting!
