### ISSUE TITLE
Maven plugin should apply recipe to all sub modules in one pass

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite-maven-plugin#349]
Currently each sub-module is parsed independently of each other, and recipe runs are applied only to a sub-module. 
It is currently impossible for a `Recipe` run by the maven plugin to look at information in sub-module A and use that information while visiting a class in sub-module B.

This behavior differs from our Gradle plugin. The Gradle plugin is able to aggregate all subprojects together into a single list of ASTs and `Recipe`s are applied to them together, rather than independently.

I'm not sure how to configure Maven to do this.

**Comment by tkvangorder** [comment]
To clarify this a bit: 

The plugin's project parser is called on each module of a multi-module project (in reactor order). The plugin correctly configures the classpath of the Java parser (using Maven's project settings) to include any transitive project dependencies. This means that the type attribution will be correct. 

However, the list of source files generated by the parser will ONLY include the java source for that module. This means that when a recipe is executed, it only operates on source files local to the current module. This will not include source files from other modules (even if they are part of a larger, multi-module build).

**Comment by tkvangorder** [comment]
This enhancement has been merged with #359
