### ISSUE TITLE
Cannot construct instance of `org.openrewrite.maven.internal.RawPom$PluginManagement`

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite-maven-plugin#356]
I was playing with snapshot version of rewrite (and rewrite-plugin), and was blocked on multi-modules maven project with the following error: 

> [INFO] --- rewrite-maven-plugin:4.24.0-SNAPSHOT:run (default-cli) @ piggymetrics ---
[INFO] Using active recipe(s) [org.openrewrite.java.cleanup.CommonStaticAnalysis]
[INFO] Using active styles(s) []
[INFO] Validating active recipes...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] piggymetrics 1.0-SNAPSHOT .......................... FAILURE [ 16.335 s]
[INFO] config 1.0.0-SNAPSHOT .............................. SKIPPED
[INFO] monitoring 0.0.1-SNAPSHOT .......................... SKIPPED
[INFO] registry 0.0.1-SNAPSHOT ............................ SKIPPED
[INFO] gateway 1.0-SNAPSHOT ............................... SKIPPED
[INFO] auth-service 1.0-SNAPSHOT .......................... SKIPPED
[INFO] account-service 1.0-SNAPSHOT ....................... SKIPPED
[INFO] statistics-service 1.0-SNAPSHOT .................... SKIPPED
[INFO] notification-service 1.0.0-SNAPSHOT ................ SKIPPED
[INFO] turbine-stream-service 0.0.1-SNAPSHOT .............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.828 s
[INFO] Finished at: 2022-05-08T22:12:32+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:4.24.0-SNAPSHOT:run (default-cli) on project piggymetrics: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.24.0-SNAPSHOT:run failed: Failed to parse pom: Cannot construct instance of `org.openrewrite.maven.internal.RawPom$PluginManagement` (although at least one Creator exists): no default no-arguments constructor found
[ERROR]  at [Source: (FileInputStream); line: 256, column: 5] (through reference chain: org.openrewrite.maven.internal.RawPom["build"]->org.openrewrite.maven.internal.RawPom$Build["pluginManagement"])
[ERROR] -> [Help 1]

Issue could be reproduced with this branch: https://github.com/murdos/piggymetrics/tree/rewrite-playground

The issue is not reproduced on an simple mono-module maven project.

NB: such an issue could have been identified by https://github.com/openrewrite/rewrite/issues/1715

**Comment by tkvangorder** [comment]
Thanks for reporting the issue this was just an issue the using the wrong constructor annotation on the new PluginManagement model. 

We do have #1715 on our backlog and realize it's important to have integration tests.

**Comment by tkvangorder** [comment]
This has been address with this commit : https://github.com/openrewrite/rewrite/commit/7a1bba2775a873fbb61d8152818eb7533bc205f1

**Comment by murdos** [comment]
Thanks for the quick fix!
