### ISSUE TITLE
Include parameters in the Maven commands "mvn rewrite:run" or "mvn rewrite:dryRun"

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite-maven-plugin#375]
Good afternoon, 

Is there a possibility to include parameters in the Maven commands "mvn rewrite:run" or "mvn rewrite:dryRun" to be able to execute a group of recipes or another, depending on the value passed? 

Thank you very much for your help.

**Comment by pway99** [comment]
Hi @josemariavillar,  Thanks for the suggestion!  A similar issue #345 exists; I hope you don't mind me closing this one, given there is a discussion in progress.
