### ISSUE TITLE
Checkstyle & Java Compatibility

### ISSUE THREAD

**Issue by jelliottp** [openrewrite/rewrite-maven-plugin#393]
I'm still having issues with Checkstyle & Java compatibility even after [1958](https://github.com/openrewrite/rewrite/issues/1958) was fixed and released in rewrite-maven-plugin 4.26.0. In a java 8 project I get this:

`Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.26.0:run failed: An API incompatibility was encountered while executing org.openrewrite.maven:rewrite-maven-plugin:4.26.0:run: java.lang.UnsupportedClassVersionError: com/puppycrawl/tools/checkstyle/api/CheckstyleException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

Any ideas? The latest rewrite-maven-plugin version I am able to run is 4.21.0. However I am finding the `exclusion` configuration not working properly in this version (appears to be fixed in 4.25.1?).

**Comment by traceyyoshima** [comment]
Hi @jelliottp, sorry about that!
 
It looks like dependabot automatically updated the [dependency](https://github.com/openrewrite/rewrite-maven-plugin/blob/b6ca86628c7aeff3e21a25ca3bcaaaf9836bf410/pom.xml#L120). I'll update the dependency and do a point release soon as I find a means to prevent the regression.

**Comment by traceyyoshima** [comment]
@jelliottp 4.26.1 is released, thanks again for the report!

**Comment by jelliottp** [comment]
Works now, thank you!
