### ISSUE TITLE
Disable checkstyle handling

### ISSUE THREAD

**Issue by simonstratmann** [openrewrite/rewrite-maven-plugin#395]
The plugin automatically detects a checkstyle plugin configuration. But the plugin execution is actually disabled and its can't be properly parsed by rewrite because of a custom property (see https://checkstyle.org/eclipse-cs/#!/properties).

We don't want the checkstyle processing. I found a way to manually enable it but no way to disable it.

Thanks.

**Comment by tkvangorder** [comment]
@simonstratmann There is now a `rewrite.checkstyleDetectionEnabled` flag that can be set to false to skip the check style logic.
