### ISSUE TITLE
Recipe not applied to sub modules

### ISSUE THREAD

**Issue by visakini** [openrewrite/rewrite-maven-plugin#396]
We are having a multi module project while configuring open rewrite recipe in parent pom.xml the recipe is not applied to the submodules.
Any configuration available for this?

**Comment by tkvangorder** [comment]
We will need more information about what is happening in your current environment. 

Can you post the configuration you are using when adding rewrite to your project? 
What version of the rewrite-maven-plugin are you using? 
Are you getting any errors/logs from rewrite?

**Comment by visakini** [comment]
<plugin>
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>4.26.0</version>
                <configuration>
                    <activeRecipes>

                        <recipe>org.openrewrite.java.security.JavaSecurityBestPractices</recipe>
                        <recipe>org.openrewrite.java.cleanup.RemoveUnusedLocalVariables</recipe>

                        <recipe>org.openrewrite.java.migrate.Java8toJava11</recipe>

                    </activeRecipes>


                </configuration>

                <dependencies>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-migrate-java</artifactId>
                        <version>1.4.3</version>
                    </dependency>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-java-security</artifactId>
                        <version>1.9.0</version>
                    </dependency>
                    



                    

                    

                    
                </dependencies>
            </plugin>

**Comment by visakini** [comment]
thisis the log when mvn clean install is used without rewrite
INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ ees-oracle-facade ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 110 source files to C:\JPMC\SIT\trunk\ees-oracle-facade\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ees-oracle-facade ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\JPMC\SIT\trunk\ees-oracle-facade\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ ees-oracle-facade ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to C:\JPMC\SIT\trunk\ees-oracle-facade\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.19:test (default-test) @ ees-oracle-facade ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-surefire-report-plugin:2.18.1:report-only (default) @ ees-oracle-facade ---
[INFO]
[INFO] --- maven-jar-plugin:2.3.1:jar (default-jar) @ ees-oracle-facade ---
[INFO] Building jar: C:\JPMC\SIT\trunk\ees-oracle-facade\target\ees-oracle-facade-20.12.23.j

**Comment by tkvangorder** [comment]
The `rewrite-maven-plugin` forks the Maven life cycle, which means that it will re-run all phases (a second time) up to process-test-resources. Can you provide the full maven log? I would expect to see `compile` twice, `testResources` twice, etc. 

Also, we fixed an issue around the calculation of the base directory in 4.27.0, can you please try with that version of the plugin?

Thanks

**Comment by visakini** [comment]
yes it works with 4.27.0
