### ISSUE TITLE
Parsing source files from an excluded module

### ISSUE THREAD

**Issue by karreiraPT** [openrewrite/rewrite-maven-plugin#426]
I have a multi-module project where some of them as included in the `exclusions` section of the plugin configuration. However, despite of no changes are applied to them I can see from the logs that they are included in the validation process. 

For instance, I have this configuration 

```
<plugin>
      <groupId>org.openrewrite.maven</groupId>
      <artifactId>rewrite-maven-plugin</artifactId>
      <version>4.34.2</version>
      <configuration>
          <activeRecipes>
              <recipe>org.openrewrite.java.format.EmptyNewlineAtEndOfFile</recipe>
          </activeRecipes>
          <configLocation>${maven.multiModuleProjectDirectory}/rewrite.yml</configLocation>
          <exclusions>
              <exclude>deploy/**</exclude>
          </exclusions>
          <skipMavenParsing>true</skipMavenParsing>
      </configuration>
</plugin>
```

and in fact no changes are applied in the `deploy` module. But, during the process it logs 

```
[INFO] Using active recipe(s) [org.openrewrite.java.format.EmptyNewlineAtEndOfFile]
[INFO] Using active styles(s) []
[INFO] Validating active recipes...
[INFO] Project [deploy] Resolving Poms...
[INFO] Skipping Maven parsing...
[INFO] Project [deploy] Parsing Source Files
```

**Comment by pway99** [comment]
Hello, 

You are correct in your assessment that diffs are not generated for members of the exclusion set even though they have been compiled and parsed.  

Every source file must be parsed to build a full type attributed AST, given that a non-excluded source file can depend on a member of the excluded set.
