### ISSUE TITLE
Support URL in the config location

### ISSUE THREAD

**Issue by gastaldi** [openrewrite/rewrite-maven-plugin#432]
It would be nice if we could specify an URL as the config location

**Comment by tkvangorder** [comment]
Closing this, the preferred way to share recipes across an organization is to package up the recipe (and its configuration) into a recipe jar and publish as an artifact.

**Comment by jkschneider** [comment]
@gastaldi Can you describe the usage pattern a bit more fully?

**Comment by jkschneider** [comment]
Sorry for the delay on this @gastaldi!

**Comment by gastaldi** [comment]
Fantastic, thank you @jkschneider !
