### ISSUE TITLE
-Drewrite.recipeArtifactCoordinates should include transitive dependencies

### ISSUE THREAD

**Issue by ge0ffrey** [openrewrite/rewrite-maven-plugin#437]
In the maven plugin, the command line option `rewrite.recipeArtifactCoordinates` does not take into account transitive dependencies, causing recipes (that are not part of rewrite upstream, so not AutoFormat)  to thrown an error.

**Reproducer**

1. Run optaplanner-migration on an optaplanner quickstart

```
git clone https://github.com/kiegroup/optaplanner-quickstarts
cd optaplanner-quickstarts
git checkout 8.27.0.Final
cd use-cases/school-timetabling
mvn clean org.openrewrite.maven:rewrite-maven-plugin:4.36.0:run -Drewrite.recipeArtifactCoordinates=org.optaplanner:optaplanner-migration:8.31.0.Final -Drewrite.activeRecipes=org.optaplanner.migration.ToLatest
```
Note: if optaplanner 8.31.0.Final is not out yet, [build optaplanner from scatch](https://github.com/kiegroup/optaplanner) and use 8.31.0-SNAPSHOT instead.

Then open `TimeTableConstraintProvider.java` and check if the roomConflict() method has changed and how.

Here's how it looks like (bad):

![image](https://user-images.githubusercontent.com/176880/201675806-6d026e5a-a242-4abc-9c81-ece5af178abd.png)

This is what it should be (good):

```
    Constraint roomConflict(ConstraintFactory constraintFactory) {
                ...
                // ... and penalize each pair with a hard weight.
                .penalize(HardSoftScore.ONE_HARD);
                .asConstraint("Room conflict");
    }
```

**Comment by tkvangorder** [comment]
Transferred. Thank you for reporting this issue!

**Comment by ge0ffrey** [comment]
Slack info:

@tkvangorder wrote:

>  It appears that we are using a custom class loader (to pick up these artifacts) when loading the environment: https://github.com/openrewrite/rewrite-maven-plugin/blob/main/src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java#L73 So, that would explain why it is finding the recipe. However, I think because we are also importing rewrite classes into the Mojo, these classes are going to be loaded with the plugin's class loader. I honestly didn't know we had added this ability. I think many folks have been using the rewrite:configure to add the plugin to pom.xml and then rewrite:remove to remove it. I know this is not quite the same experience.I think we will have to investigate/unify how class loading is done before this will work correctly.


@kmclarnon wrote:
> ClassGraph instances allow overriding the classpath/classloaders that are scanned, so making ClassGraph use the set of jars that are used to construct the recipe should be possible.  It seems to me that in general you would want to prefer the recipe's classpath rather than the plugin or the project you're operating on but there are probably usecases I'm not aware of

But it sounds like Tim's solution sounds simplest (if it works): " The maven plugin has init and remove goals to at least for now make it a two step: first init by itself, then run and remove together as a second step."

**Comment by tkvangorder** [comment]
@nmck257 Thank you for the fix!

@ge0ffrey We believe this should work correctly with `4.38.0` and we are planning on doing a release tomorrow.

**Comment by tkvangorder** [comment]
If, for some reason, this is not resolved, we can re-open.
