### ISSUE TITLE
Performance issues printing Result / Recipe Stack summary

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite-maven-plugin#486]
With the latest release, we've seen considerable lag in the summary printed after recipe execution:
specifically, between the lines like "Changes have been made to my/project/file.txt" and the subsequent recipe stack.

I'm seeing a trend roughly like:
- A file touched by ~1 recipe takes ~14ms to generate its recipe stack summary for printing in all tested versions
- In the previous three versions, a file touched by ~9 recipes takes ~120ms to do the same (feels like ~linear scaling, 9*14=126)
- But in the latest release, a file touched by ~9 recipes takes ~176ms, roughly ~50% longer than the previous versions

Anecdotally, I've seen delays over 1m for heavily-touched files in large projects after running large recipes (but those were private recipes/projects, so, harder to reproduce for public consumption). My intuition is that some change in the latest release has worsened the scaling of this code from ~linear to ~exponential per number of recipes.

## Data / Methodology

Benchmarks were gathered by running the Spring Boot 2.7 recipe on [this revision of spring-petclinic on spring boot 2.3.0](https://github.com/spring-projects/spring-petclinic/commit/c9230c37b9e6aac71d0724eccf3236dde034ce27) with various versions of the rewrite-maven-plugin / rewrite-spring.

| Plugin / rewrite-spring version| pom.xml | PetTypeFormattersTest.java |
| -------- | -- | -- |
| 4.39.0 / 4.32.0 | 176ms | 13ms |
| 4.38.1 / 4.31.0 | 128ms | 14ms |
| 4.37.0 / 4.30.0 | 112ms | 13ms |
| 4.36.0 / 4.29.0 | 124ms | 16ms |

The value captured in the above table is defined as the delay between the "These recipes would make changes..." line and the subsequent line, for the relevant file, average across three executions. Sample logs below.

> 27917 [INFO] Running recipe(s)...
47509 [WARNING] These recipes would make changes to pom.xml:
47689 [WARNING]     org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_7
47689 [WARNING]         org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_6
47690 [WARNING]             org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_5
47690 [WARNING]                 org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_4
47690 [WARNING]                     org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_3
47691 [WARNING]                         org.openrewrite.maven.UpgradeDependencyVersion: {groupId=org.springframework.boot, artifactId=\*, newVersion=2.3.x, overrideManagedVersion=true, retainVersions=[]}
47691 [WARNING]                         org.openrewrite.maven.UpgradeParentVersion: {groupId=org.springframework.boot, artifactId=spring-boot-starter-parent, newVersion=2.3.x, retainVersions=[]}
47691 [WARNING]                     org.openrewrite.maven.UpgradeDependencyVersion: {groupId=org.springframework.boot, artifactId=\*, newVersion=2.4.x, overrideManagedVersion=true, retainVersions=[]}
47691 [WARNING]                     org.openrewrite.maven.UpgradeParentVersion: {groupId=org.springframework.boot, artifactId=spring-boot-starter-parent, newVersion=2.4.x, retainVersions=[]}
47691 [WARNING]                     org.openrewrite.maven.RemoveExclusion: {groupId=org.springframework.boot, artifactId=spring-boot-starter-test, exclusionGroupId=org.junit.vintage, exclusionArtifactId=junit-vintage-engine}
47691 [WARNING]                 org.openrewrite.maven.UpgradeParentVersion: {groupId=org.springframework.boot, artifactId=spring-boot-starter-parent, newVersion=2.5.x, retainVersions=[]}
47691 [WARNING]             org.openrewrite.maven.UpgradeDependencyVersion: {groupId=org.springframework.boot, artifactId=*, newVersion=2.6.x, overrideManagedVersion=true, retainVersions=[]}
47691 [WARNING]             org.openrewrite.maven.UpgradeParentVersion: {groupId=org.springframework.boot, artifactId=spring-boot-starter-parent, newVersion=2.6.x, retainVersions=[]}
47691 [WARNING]         org.openrewrite.maven.UpgradeParentVersion: {groupId=org.springframework.boot, artifactId=spring-boot-starter-parent, newVersion=2.7.x, retainVersions=[]}
47691 [WARNING] These recipes would make changes to src\main\resources\application-mysql.properties:
47695 [WARNING]     org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_7
47695 [WARNING]         org.openrewrite.java.spring.boot2.SpringBootProperties_2_7
47695 [WARNING]             org.openrewrite.java.spring.ChangeSpringPropertyKey: {oldPropertyKey=spring.datasource.initialization-mode, newPropertyKey=spring.sql.init.mode}
47695 [WARNING] These recipes would make changes to src\main\resources\application.properties:
47708 [WARNING]     org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_7
47708 [WARNING]         org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_6
47708 [WARNING]             org.openrewrite.java.spring.boot2.SpringBootProperties_2_6
47708 [WARNING]                 org.openrewrite.java.spring.ChangeSpringPropertyKey: {oldPropertyKey=spring.resources.cache.cachecontrol.max-age, newPropertyKey=spring.web.resources.cache.cachecontrol.max-age}
47709 [WARNING]         org.openrewrite.java.spring.boot2.SpringBootProperties_2_7
47709 [WARNING]             org.openrewrite.java.spring.ChangeSpringPropertyKey: {oldPropertyKey=spring.datasource.data, newPropertyKey=spring.sql.init.data-locations}
47709 [WARNING]             org.openrewrite.java.spring.ChangeSpringPropertyKey: {oldPropertyKey=spring.datasource.schema, newPropertyKey=spring.sql.init.schema-locations}
47709 [WARNING] These recipes would make changes to src\test\java\org\springframework\samples\petclinic\owner\PetTypeFormatterTests.java:
47720 [WARNING]     org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_7
47720 [WARNING]         org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_6
47720 [WARNING]             org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_5
47720 [WARNING]                 org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_4
47720 [WARNING]                     org.openrewrite.java.testing.junit5.JUnit5BestPractices
47720 [WARNING]                         org.openrewrite.java.testing.junit5.StaticImports
47720 [WARNING]                             org.openrewrite.java.UseStaticImport: {methodPattern=org.junit.jupiter.api.Assertions *(..)}
47824 [WARNING] Patch file available:
47824 [WARNING]     I:\ds\projects\tmp\spring-petclinic\target\rewrite\rewrite.patch
47824 [WARNING] Run 'mvn rewrite:run' to apply the recipes.

...Using commands like this:
```
mvn clean org.openrewrite.maven:rewrite-maven-plugin:4.39.0:dryRun -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-spring:4.32.0 -DactiveRecipes=org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_7 -Dorg.slf4j.simpleLogger.showDateTime=true -Dcheckstyle.skip > logs-dry-4.39.0
```

**Comment by sambsnyd** [comment]
Appreciate the analysis, thank you for putting this together

**Comment by nmck257** [comment]
Ran the same test (fewer repetitions) on a SB 1.5.1 revision of petclinic:

| Plugin / rewrite-spring version| pom.xml | PetTypeFormattersTest.java |
| -------- | -- | -- |
| 4.39.0 / 4.32.0 | 673ms | 106ms |
| 4.38.1 / 4.31.0 | 477ms | 81ms |
| 4.37.0 / 4.30.0 | (error) | (error) |
| 4.36.0 / 4.29.0 | 177ms | 81ms |

It's not quite apples-to-apples, since PetTypeFormatterTest gets hit by a small handful of recipes when coming from 1.5.1, but I think it still shows something of a trend

**Comment by nmck257** [comment]
Probably should've checked a method profiler sooner -- ~99% of sample were within `getEstimatedEffortPerOccurrence` between `CompositeRecipe` and `DeclarativeRecipe`, mostly during the `Duration` arithmetic. I'll probably play with some optimizations to that code locally.

**Comment by nmck257** [comment]
Just pushed an optimization https://github.com/openrewrite/rewrite/commit/7633b1224fb53d376726e52ee6bb177f5b9dab6d

Comparing to the metrics in my previous comment:
| Plugin / rewrite-spring version| pom.xml | PetTypeFormattersTest.java |
| -------- | -- | -- |
| New snapshot | 362ms | 84ms|
| 4.39.0 / 4.32.0 | 673ms | 106ms |
| 4.38.1 / 4.31.0 | 477ms | 81ms |
| 4.37.0 / 4.30.0 | (error) | (error) |
| 4.36.0 / 4.29.0 | 177ms | 81ms |

I'm setting this down for now, but glancing at the profiler, the next biggest offender is all the ArrayList add/copy/etc operations during `CompositeRecipe::getDataTableDescriptors`
cc @jkschneider since you've been in that code very recently

**Comment by nmck257** [comment]
Closing this with the enhancements from https://github.com/openrewrite/rewrite/pull/3024

If we see performance issues in this area again, then the next things I considered trying were:
* Moving `DeclarativeRecipe` descriptors into a `private static Map<String, RecipeDescriptor> cache`, under the assumption that every instance of a declarative recipe with a particular name will be identical and have identical descriptors
* Adjusting the DataTableDescriptor generation, to avoid the current scenario where every single recipe includes 3 global tables in its list, and every single `CompositeRecipe` then dedupes those tables from a `List` for every member recipe; in one profiler dump during descriptor generation, 38% of samples were in `DataTableDescriptor::equals` within `ArrayList::contains`
  * Simply swapping the data table descriptors to a `Set` might be sufficient
