### ISSUE TITLE
Link to blog post is wrong

### ISSUE THREAD

**Issue by khmarbaise** [openrewrite/rewrite-maven-plugin#490]
The link to the blog post https://blog.soebes.de/blog/2020/08/18/itf-part-i/ is wrong.

**Comment by timtebeek** [comment]
Fixed the link just now; good seeing you here!

Missed you in the hallway track at FOSDEM, but if there's ever anything we can help with let us know :)

**Comment by khmarbaise** [comment]
I've provided a pr to fix this. I had been in the dev room for the openrewrite lecture 👍

**Comment by timtebeek** [comment]
Yes glad to hear! If you ever want to apply some recipes in bulk we have 90 Apache Maven repositories in https://public.moderne.io ; I had done some earlier pull requests manually to apache/maven-wrapper for their JUnit 5 migration; we can scale that up if you'd like. I'm available in the Foojay Slack if it helps.
