### ISSUE TITLE
Remove not needed dependency to org.twdata.maven:mojo-executor

### ISSUE THREAD

**Issue by khmarbaise** [openrewrite/rewrite-maven-plugin#492]
The dependency:
```xml
       <dependency>
            <groupId>org.twdata.maven</groupId>
            <artifactId>mojo-executor</artifactId>
            <version>2.4.0</version>
            <scope>test</scope>
        </dependency>
```
is currently not being used. So it should be removed.

**Comment by timtebeek** [comment]
Noticed you've already started a [branch in your fork](https://github.com/openrewrite/rewrite-maven-plugin/compare/main...khmarbaise:rewrite-maven-plugin:issue-492); feel free to open a pull request and I'll merge that as soon as possible.
