### ISSUE TITLE
The integration test ConfigureMojoITNoActiveRecipe is currently not being executed

### ISSUE THREAD

**Issue by khmarbaise** [openrewrite/rewrite-maven-plugin#494]
The integration test `ConfigureMojoITNoActiveRecipe` is currently not being executed based on the naming pattern. The integration tests should follow `*IT.java`...furthermore based on naming of the other it's it should be named like `DiscoverNoActiveRecipeIT`? WDYT?

**Comment by timtebeek** [comment]
Thank you for the thorough look into our plugin! :)
