### ISSUE TITLE
Remove public modifier from integration tests classes

### ISSUE THREAD

**Issue by khmarbaise** [openrewrite/rewrite-maven-plugin#496]
Currently all integration tests are defined like:
```java
..
public class BasicIT {
..
}
```
which is not necessary.

**Comment by timtebeek** [comment]
That's embarrassing; [we even have a recipe for that](https://docs.openrewrite.org/reference/recipes/java/testing/cleanup/testsshouldnotbepublic); let me see if I can run that quickly. :)

**Comment by timtebeek** [comment]
Thanks again! We have a plan internally to apply our recipes to our own code continuously; thanks for the reminder to move that up in priority!
