### ISSUE TITLE
Add support for parsing `Kotlin` sources

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-maven-plugin#526]
This issue will track adding support for parsing `.kt` sources with the `KotlinParser` to the maven plugin.

**Comment by jwillebrands** [comment]
Heya. Is there anything we can do to move forward on this? Our company unfortunately chose Maven for both Java and Kotlin projects and with a growing Kotlin codebase would benefit greatly from this support. Happy to help out if need be.

**Comment by Wallman** [comment]
@jwillebrands This seems to be coming soon :) 

https://rewriteoss.slack.com/archives/C01A843MWG5/p1695762656099699?thread_ts=1695371865.357389&channel=C01A843MWG5&message_ts=1695762656.099699

**Comment by Wallman** [comment]
Seems to be solved with https://github.com/openrewrite/rewrite-maven-plugin/pull/641

**Comment by knutwannheden** [comment]
Please note that this is not yet part of any release, but that should follow this or next week.

**Comment by knutwannheden** [comment]
I think it will come with the next patch release. You can see this by checking the commits since that release: https://github.com/openrewrite/rewrite-maven-plugin/compare/v5.8.1...main

**Comment by knutwannheden** [comment]
Although in the 5.9.0-SNAPSHOT build it should be included.

**Comment by Wallman** [comment]
https://github.com/openrewrite/rewrite-maven-plugin/releases/tag/v5.9.1
