### ISSUE TITLE
Add KotlinParser to the maven plugin.

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-maven-plugin#538]
The majority of Kotlin sources in the default repository list as of 4/5/23 are from Maven projects which causes the files to be `Quarks`.

**Comment by timtebeek** [comment]
Now likely handled through https://github.com/search?q=repo%3Aopenrewrite%2Frewrite-all%20kotlin&type=code , which should make it's way here.

**Comment by traceyyoshima** [comment]
Closing as a duplicate of https://github.com/openrewrite/rewrite-maven-plugin/issues/526.
We found that most of the Kotlin projects were Gradle.
However, many of the Gradle projects used the Android plugin.

Until recently, no one had asked for the KotlinParser in a maven project, so it hasn't been a priority.
