### ISSUE TITLE
Honor maven debug mode to log progress

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-maven-plugin#544]
In Maven, we can run in debug mode running `-X` 

```
 -X,--debug                             Produce execution debug output
```

Currently, the plugin does not honor this parameter, and it is unclear what is needed to enable debug logs

Ideally, I'd like to run this: 

```shell
 mvn -X -U org.openrewrite.maven:rewrite-maven-plugin:run Drewrite.activeRecipes=org.openrewrite.maven.OrderPomElements
```

And get all the internal `debug` logs of this plugin

**Comment by yeikel** [comment]
Also, this is how this is implemented in Maven

https://github.com/apache/maven/blob/9e51a8fe9566a538b1ddb41a0aab2a710b6b88c1/maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java#L454-L460

it should be possible to implement something similar here

**Comment by timtebeek** [comment]
Thanks for the detailed report & offer to implement it @yeikel !

**Comment by yeikel** [comment]
@timtebeek Question question, what logging framework is in use here?

While looking into implementing this, I was surprised that the maven code is not respected when it just calls the 
` slf4j` library

**Comment by yeikel** [comment]
Never mind, I was able to find some info using the debugger 

![image](https://user-images.githubusercontent.com/8935151/232826078-8aadce11-dc0d-4f3d-b030-ac58df6a8c32.png)

**Comment by timtebeek** [comment]
Ah great; yes that'll do; I'd not looked into the specifics of logging yet either, glad to see you worked it out.
Traveling again, so not as responsive at all times as I'd hope. Let me know if there's any further issues!

**Comment by shawware** [comment]
I'd like to see this implemented. My use case is processing a large monolith on a CI/CD server to get access to the RAM required. All goes pretty well until the CI/CD build system kills my job after failing to detect any log output for 20 minutes. Having regular output while applying the recipes would help prevent this.

**Comment by yeikel** [comment]
@timtebeek Unfortunately, I did not get a chance to pick this up yet, so it is sensible to reopen it to the community if you can

**Comment by timtebeek** [comment]
Yes sure; appreciate you communicating that clearly here. Anyone willing is welcome to step up and bring this closer!

**Comment by timtebeek** [comment]
We've built up some experience with using `org.apache.maven.execution.ExecutionEvent` and `org.apache.maven.execution.ExecutionListener` to report progress to the Moderne CLI, but have not yet found to time to translate that into progress reports for the rewrite-maven-plugin. Posting this here as a reminder or starting point.

**Comment by timtebeek** [comment]
Rather than log every file parsed, we recommend folks try out [the Moderne CLI](https://docs.moderne.io/user-documentation/getting-started/cli-intro), as that provides a convenient progress indicator for large projects. We don't expect to offer the same progress indicators on the Maven and Gradle plugins, as the richness in the progress output would be next to impossible to replicate given the limits to Maven and Gradle log outputs. Hope that helps!
