### ISSUE TITLE
dryRun - Split patch file for each recipe

### ISSUE THREAD

**Issue by philippe-granet** [openrewrite/rewrite-maven-plugin#553]
Hi,
When using `rewrite:dryRun` goal and having a lot of recipes, I want to have a patch file for each recipe.
I try to implement that: https://github.com/openrewrite/rewrite-maven-plugin/commit/60eafd1522b7aa1a118639a8f1e84cdf72c4ce8f
For performance, I put "Resolving Pom" and "Parsing source files" in cache:
https://github.com/openrewrite/rewrite-maven-plugin/commit/60eafd1522b7aa1a118639a8f1e84cdf72c4ce8f#diff-9ed36616c9e66b19e95c21bbb881d89a04b37e682ae34e7c8e7016e6628db799R172
and I loop over recipes:
https://github.com/openrewrite/rewrite-maven-plugin/commit/60eafd1522b7aa1a118639a8f1e84cdf72c4ce8f#diff-9ed36616c9e66b19e95c21bbb881d89a04b37e682ae34e7c8e7016e6628db799R234

I test with 2 recipes (`/org.openrewrite.java.RemoveUnusedImports` and `org.openrewrite.java.AddApache2LicenseHeader`), it seems to work:
```
[WARNING] Patch file available:
[WARNING]     /mnt/c/git/rewrite-maven-plugin/target/rewrite/org.openrewrite.java.RemoveUnusedImports.patch
...
[WARNING] Patch file available:
[WARNING]     /mnt/c/git/rewrite-maven-plugin/target/rewrite/org.openrewrite.java.AddApache2LicenseHeader.patch
```
Full log:
```
[INFO] --- rewrite-maven-plugin:4.46.0-SNAPSHOT:dryRunSplit (default-cli) @ rewrite-maven-plugin ---
[INFO] Using active recipe(s) [org.openrewrite.java.RemoveUnusedImports]
[INFO] Using active styles(s) []
[INFO] Validating active recipes...
[INFO] Running recipe(s)...
[INFO] Project [rewrite-maven-plugin] Resolving Poms...
[INFO] Project [rewrite-maven-plugin] Parsing source files
[WARNING] These recipes would make changes to src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java:
[WARNING]     org.openrewrite.java.RemoveUnusedImports
[WARNING] These recipes would make changes to .mvn/wrapper/MavenWrapperDownloader.java:
[WARNING]     org.openrewrite.java.RemoveUnusedImports
[WARNING] Patch file available:
[WARNING]     /mnt/c/git/rewrite-maven-plugin/target/rewrite/org.openrewrite.java.RemoveUnusedImports.patch
[WARNING] Run 'mvn rewrite:run' to apply the recipes.
[INFO] Using active recipe(s) [org.openrewrite.java.AddApache2LicenseHeader]
[INFO] Using active styles(s) []
[INFO] Validating active recipes...
[INFO] Running recipe(s)...
[WARNING] These recipes would make changes to src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java:
[WARNING]     org.openrewrite.java.AddApache2LicenseHeader
[WARNING]         org.openrewrite.java.AddLicenseHeader: {licenseText=Copyright 2023 the original author or authors.
...
[WARNING] Patch file available:
[WARNING]     /mnt/c/git/rewrite-maven-plugin/target/rewrite/org.openrewrite.java.AddApache2LicenseHeader.patch
[WARNING] Run 'mvn rewrite:run' to apply the recipes.
```

Do you think it is someting that could be implemented in the rewrite-maven-plugin?

**Comment by rpau** [comment]
Thanks! this might be definitely interesting. Could you elaborate what is the workflow that you are interested to provide and why this workflow is more beneficial than a single patch?

**Comment by timtebeek** [comment]
We've discussed this internally as well, but have concerns with regards to how any individual patch files are likely to be inter dependent. Recipes are applied in a [defined order](https://github.com/openrewrite/rewrite/issues/3320#issuecomment-1593367201), with the output of one assumed to be the input for the next. As such there's little perceived value right now in creating multiple patch files, as they will have to be applied in order for things to work out.

So while we appreciate the suggestion and work you've put towards this, pending further details about your use case, we don't feel this is something to explore further in the near future. Feel free to still chime in with your point of view, and we can weigh reopening this issue.
