### ISSUE TITLE
maven.plugin.validation warning about usage of plexus-container-default

### ISSUE THREAD

**Issue by jjank** [openrewrite/rewrite-maven-plugin#561]
Hi there!

Just ran a migration with maven `3.9.2`

```sh
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run \
  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-testing-frameworks:RELEASE \
  -Drewrite.activeRecipes=org.openrewrite.java.testing.assertj.JUnitToAssertj \
  -Dmaven.plugin.validation=VERBOSE
```

And it issued the following warning:

```
[WARNING]  * org.openrewrite.maven:rewrite-maven-plugin:4.46.0
[WARNING]   Declared at location(s):
[WARNING]    * unknown
[WARNING]   Used in module(s):
[WARNING]    * *********omitted*********:1.0-SNAPSHOT (pom.xml)
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin depends on plexus-container-default, which is EOL
```

I _think_ this is a new warning that only appears in more recent maven versions. I guess many other maven plugins will have the same issue. In fact, even `maven-surefire-plugin` has the same `plexus-container-default` warning so we're not alone 😅 

The [Plexus page](https://codehaus-plexus.github.io/plexus-containers/plexus-container-default/) suggests [sisu.plexus](https://github.com/eclipse/sisu.plexus) as a replacement.

**Comment by jjank** [comment]
I just had a look at the dependency tree of `rewrite-maven-plugin` (maybe I should have done that before opening the issue 🙈  ) and saw that `plexus-container-default` comes as a transitive dependency of `plexus-interactivity-api`:
```
...
[INFO] +- org.codehaus.plexus:plexus-interactivity-api:jar:1.1:compile
[INFO] |  +- org.codehaus.plexus:plexus-utils:jar:3.3.0:compile
[INFO] |  \- org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile
...
```

So feel free to close this issue if you think this problem should rather be solved upstream 👍

**Comment by timtebeek** [comment]
Thanks for reporting this here @jjank ! Indeed seems like [something to fix in plexus-interactivity-api](https://github.com/codehaus-plexus/plexus-interactivity/blob/5dfa486ddbb44613149648b2f1162c8a230551ed/plexus-interactivity-api/pom.xml#L26-L27), possibly by merely replacing the current dependency with the sisu.plexus shim, as you've pointed out.

We can propose a single fix in a pull request to see this one resolved here. They have [20+ usages across multiple repositories](https://github.com/search?q=org%3Acodehaus-plexus+plexus-container-default+language%3A%22Maven+POM%22&type=code&l=Maven+POM); maybe after the first one @slachiewicz would be open to a bulk fix applied to all codehaus-plexus repositories?

**Comment by timtebeek** [comment]
Thanks! That will also work; the changes you applied there look like something we could capture in a recipe; let us know if that would be of interest if you have to make more of such changes.

**Comment by jjank** [comment]
@timtebeek aww ❤️ 

Certainly sounds interesting! In which `rewrite-*` would such a recipe belong? 🤔

**Comment by jjank** [comment]
> Probably the latter is better, since there's more Maven recipes in there already. We can move & re-purpose this issue there if needed.

Sounds reasonable. When I find some time I'll try to work on said recipe 😄

**Comment by timtebeek** [comment]
It looks like at plexus they've already reduced the number of dependencies on `plexus-container-default` down to seven, whereas we found 20+ in May. That reduces the need for a recipe to clean that up still. There's not yet been a release of `plexus-interactivity-api`, but with an exclude here we're no longer getting the warning that started this issue. Closing the issue now; thanks all!
