### ISSUE TITLE
Incorrect classifier reported for `pom` packaging

### ISSUE THREAD

**Issue by algomaster99** [openrewrite/rewrite-maven-plugin#579]
I was working on #570, and I also discovered this. The maven reactor build classifies it as `pom`, but the rewrite plugin reports `jar`.

## What version of OpenRewrite are you using?

I am using

- OpenRewrite 7.18.0
- Maven/Gradle plugin v5.0.0

## How are you running OpenRewrite?

I am using the Maven plugin and I run the following command
```sh
mvn org.openrewrite.maven:rewrite-maven-plugin:5.0.0:cyclonedx --fail-at-end
```
on one of the existing [test resources](https://github.com/openrewrite/rewrite-maven-plugin/tree/main/src/test/resources-its/org/openrewrite/maven/RewriteCycloneDxIT/multi_module_with_independent_modules).

## What is the smallest, simplest way to reproduce the problem?

1. Go to the test resource directory.
2. Run the maven plugin.

## What did you expect to see?

```xml
<component bom-ref="pkg:maven/org.openrewrite.maven/multi_module_with_independent_modules@1.0?type=pom" type="library">
    <group>org.openrewrite.maven</group>
    <name>multi_module_with_independent_modules</name>
    <version>1.0</version>
    <scope>required</scope>
    <purl>pkg:maven/org.openrewrite.maven/multi_module_with_independent_modules@1.0?type=pom</purl>
</component>
```

## What did you see instead?

```xml
<component bom-ref="pkg:maven/org.openrewrite.maven/multi_module_with_independent_modules@1.0?type=jar" type="library">
    <group>org.openrewrite.maven</group>
    <name>multi_module_with_independent_modules</name>
    <version>1.0</version>
    <scope>required</scope>
    <purl>pkg:maven/org.openrewrite.maven/multi_module_with_independent_modules@1.0?type=jar</purl>
</component>
```

Notice the value of `type` in pURL.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Yes

**Comment by timtebeek** [comment]
Thank you for reporting another issue, with clear minimal steps to reproduce. Also appreciate that you indicated you'd be interested in contributing a fix; let me know how we can best support you in that! Also welcome to [drop by our Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA) if that helps.

**Comment by timtebeek** [comment]
Glad to year you've been able to pin point it; from https://github.com/algomaster99/rewrite-maven-plugin/commit/cfc9f7524340aecf356c74d53f704e87e6471f29 it looks like you're working on a reproducer and maybe even potential fix? Should I wait for that before we explore here?

**Comment by algomaster99** [comment]
Since the bug was in `rewrite-maven` module, I submitted a PR there - https://github.com/openrewrite/rewrite/pull/3302.

**Comment by timtebeek** [comment]
Thanks a lot @algomaster99 , both for the report & detailed fix!

I'm assuming the fix upstream will cascade the fix here; let me know if that's not immediately the case.

**Comment by algomaster99** [comment]
> I'm assuming the fix upstream will cascade the fix here;

I think so too. I am waiting for the SNAPSHOT to be published so that I can test it. I am not sure how to install SNAPSHOT packages locally with Gradle.

**Comment by timtebeek** [comment]
To install snapshots locally you can use `./gradlew publishToMavenLocal`, or `./gradlew pTML` for short.
Otherwise the new builds should be coming up in [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions).

**Comment by algomaster99** [comment]
I installed it locally and have used the test [here](https://github.com/algomaster99/rewrite-maven-plugin/commit/cfc9f7524340aecf356c74d53f704e87e6471f29) to confirm. It works!

**Comment by timtebeek** [comment]
Great to hear, thanks a lot!
