### ISSUE TITLE
`java.specification.version` should be used when no java version for Maven source and target can be retrieved

### ISSUE THREAD

**Issue by fabapp2** [openrewrite/rewrite-maven-plugin#593]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.1.2
- Maven plugin v5.2.2

## How are you running OpenRewrite?

Programmatically calling `MavenMojoProjectParser.generateProvenance(MavenProject)` 

## What is the smallest, simplest way to reproduce the problem?
1. Instantiate a `MavenMojoProjectParser` with null and default values
2. Create a `new MavenProject` 
3. Call `MavenMojoProjectParser.generateProvenance(mavenProject)`

 
## What did you expect to see?
I'd expect `java.specification.version` to be used instead of `java.runtime.version` 
Then the `JavaVersion` marker has a `sourceCompatibility` and `targetCompatibility` of `17` (in my case)

## What did you see instead?
 The `JavaVersion` marker has a `sourceCompatibility` and `targetCompatibility` set as the full version, e.g. `17.0.2+8-LTS`

## What is the full stack trace of any errors you encountered?
-

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
I'll provide a PR.

**Comment by fabapp2** [comment]
See https://github.com/openrewrite/rewrite-maven-plugin/pull/594

**Comment by fabapp2** [comment]
Maybe misunderstood the intent of API, `majorRealeaseVersion` and `majorTargetVersion` having `java.specification.value`.
I'd still assume `targetCompatibility` and `sourceCompatibility` should contain the specification values as they would be used in Maven because of their similarity in name to the Maven concept of target and source compatibility. 
However, if your intent was a different one, just close the issue and the PR.

**Comment by knutwannheden** [comment]
@fabapp2 This sounds reasonable. Thanks for reporting and the PR!
