### ISSUE TITLE
Run recipes blocking

### ISSUE THREAD

**Issue by JoeCqupt** [openrewrite/rewrite-maven-plugin#595]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.1.6
- Maven/Gradle plugin v5.2.6
- rewrite-spring  v5.0.3

## How are you running OpenRewrite?

I am using the Maven plugin, and my project consist of 27 module
```bash
mvn -DskipTests=true -T 1C  org.openrewrite.maven:rewrite-maven-plugin:5.2.6:run    -Drewrite.recipeArtifactCoordinates=... -Drewrite.activeRecipes=org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_0
```

## What is the smallest, simplest way to reproduce the problem?

```bash
mvn -DskipTests=true -T 1C  org.openrewrite.maven:rewrite-maven-plugin:5.2.6:run    -Drewrite.recipeArtifactCoordinates=... -Drewrite.activeRecipes=org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_0
```

## What did you expect to see?

mvn build success

## What did you see instead?

mvn build blocking . it blocking over 1 hour
<img width="621" alt="image" src="https://github.com/openrewrite/rewrite-maven-plugin/assets/12369652/7ee2217b-d49e-49f9-b74f-713b40d1dac6">

## What is the full stack trace of any errors you encountered?

none

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

I do not have the ability to find the cause of this problem, and I am happy to fix this problem

**Comment by knutwannheden** [comment]
Most likely you need to give your JVM a bit more memory, as the LST models require quite a lot of memory (in addition to the AST already loaded into memory by the Java compiler).

I suggest you try to prefix your command with something like `MAVEN_OPTS=-Xmx4g` as in:
```sh
MAVEN_OPTS=-Xmx4g mvn -DskipTests=true -T 1C  org.openrewrite.maven:rewrite-maven-plugin:5.2.6:run
```

**Comment by timtebeek** [comment]
Hi @JoeCqupt ! You'll want to upgrade to at least rewrite-spring 5.0.4, but most likely the latest release, which is 5.0.5 currently:
https://github.com/openrewrite/rewrite-spring/releases
These specifically address the performance issues.

**Comment by timtebeek** [comment]
As we've seen this issue reported a couple times before, for instance in https://github.com/openrewrite/rewrite-spring/issues/384 , I hope you don't mind me closing this issue already. I trust that 5.0.5 will resolve your issues, but if not feel free to chime back in here!

**Comment by knutwannheden** [comment]
@timtebeek Yes, you are right. While it isn't visible from the command, this is most likely due to an old version of the `org.openrewrite.recipe:rewrite-spring` artifact being used.
