### ISSUE TITLE
Investigate automating docs

### ISSUE THREAD

**Issue by mike-solomon** [openrewrite/rewrite-maven-plugin#602]
Right now, we rely on manually updating the [Maven plugin docs](https://docs.openrewrite.org/reference/rewrite-maven-plugin). Theoretically, we could use something like [the maven docc plugin](https://maven.apache.org/plugin-developers/plugin-documenting.html) to automate the creation of docs for this plugin.

We could then invoke this new goal and place the HTML in some `target/` directory that we could publish.

[Related Gradle issue](https://github.com/openrewrite/rewrite-gradle-plugin/issues/215)

[Related internal Slack thread](https://moderneinc.slack.com/archives/C04HLU7FG31/p1689693646849119?thread_ts=1689619338.215239&cid=C04HLU7FG31)

Suggested by: @timtebeek

**Comment by timtebeek** [comment]
Added a quick first attempt in #603 ; needs more work to finish that, but it's a start to take over whenever you have time.

**Comment by mike-solomon** [comment]
This has been completed (https://github.com/openrewrite/rewrite-maven-plugin/pull/608)

see: https://openrewrite.github.io/rewrite-maven-plugin/
