### ISSUE TITLE
Execute the rewrite-maven-plugin over a no maven target directory (no necesary existing pom file) 

### ISSUE THREAD

**Issue by danipenaperez** [openrewrite/rewrite-maven-plugin#605]
## What problem are you trying to solve?
It seems strange to me that some goal of the rewrite-maven-plugin using `@mojo(requiresProject=false)` has not been configured. Many recipes would not need a pom to run, such as updating some properties files in a directory.

## Describe the solution you'd like
The `@Mojo` annotation at [RewriteRunMojo.java](https://github.com/openrewrite/rewrite-maven-plugin/blob/main/src/main/java/org/openrewrite/maven/RewriteRunMojo.java) inherit the default "true" value.
Ref: [https://maven.apache.org/plugin-tools/maven-plugin-annotations/apidocs/org/apache/maven/plugins/annotations/Mojo.html#requiresProject--](https://maven.apache.org/plugin-tools/maven-plugin-annotations/apidocs/org/apache/maven/plugins/annotations/Mojo.html#requiresProject--)

Would be nice to maintain the current run goal, but create new goal with requiresProject to false, that enable to execute the recipes in case that the recipe does not need a pom information context.

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?

Looking further in classes I saw this, maybe will be need a fork in the hierarchy  that not expects the MavenProject definition (pom.xml)...

```java
public abstract class AbstractRewriteMojo extends ConfigurableRewriteMojo {

    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    protected MavenProject project;
```

**Comment by timtebeek** [comment]
To run against non-Maven & non-Gradle projects we now recommend [using the Moderne CLI](https://docs.moderne.io/user-documentation/getting-started/cli-intro), as that will properly discover and hand off resources to the correct parsers, which we normally delegate to Maven and Gradle in the plugin. The CLI then allows you to run recipes against the resources discovered, to indeed update properties and other files in any directory.
