### ISSUE TITLE
Support negative matchers on exclusions, to force inclusion after a broader exclude

### ISSUE THREAD

**Issue by thomaszub** [openrewrite/rewrite-maven-plugin#612]
## What problem are you trying to solve?

We use currently the exclusion list to exclude XMLs from parsing as we have projects with many and big XML files leading to problems with the parsing. Now we would like to generally exclude XML files and include some XML files like logback configurations. 

## Describe the solution you'd like

Analagous to the exclusion list, add a inclusion list to the maven configuration which is checked before the exclusion list to allow certain kind of files to be included in the parsing.

## Have you considered any alternatives or workarounds?

Alternatively the exclusion list could be extended to allow negative matching for files. 

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?

Yes, I could/would make a PR for this feature request.

**Comment by timtebeek** [comment]
Hi @thomaszub ; thanks for your suggestion and offer to help out. We have some concerns with regards to complexity though on the interplay between includes and excludes, as this has come up before and was decided at the time to become complex.

I do like your suggestion for negative matches in the exclude list, analogous to how .gitignore files allow to skip files in an exclude. Not quite sure of that would fully work, but it's at least simpler in terms of configuration options. I think we'd need to validate this option some more before we put a lot of effort in, but certainly interesting to explore briefly.

I do wonder what parser errors you're getting with those XML files though; ideally we'd fix this to remove the need for any additions here.

**Comment by timtebeek** [comment]
Not yet sure if we should support this; but definitely interested in the parser errors you're seeing @thomaszub ; that would be the hopefully easiest way to close this issue, with broader applicability and less configuration options to document and maintain.

**Comment by thomaszub** [comment]
These were mainly big XMLs and/or broken XMLs for test cases which made a problem. I close the issue as the added complexity would not pay off.

**Comment by timtebeek** [comment]
Thanks for chiming in with the offer to help though; it's always a balance of weigh how common a use case is, versus having to take on questions and maintenance around options going forward. I hope you found a suitable solution internally to get going.

In [the Moderne CLI](https://moderneinc.github.io/moderne-cli/) we've taken to exclude files larger than 10MB, and our parsers should already [convert any exceptions during parsing into parser errors](https://github.com/openrewrite/rewrite/blob/a301363dcb75b70cb2cb09a6333eb2742857ddd2/rewrite-xml/src/main/java/org/openrewrite/xml/XmlParser.java#L60-L62), such that you ideally shouldn't be affected by those either.

Feel free to open a dedicated issue is you still have parse issues tripping up your recipe runs! :)
