### ISSUE TITLE
file with .yaml extension is not recognized as custom rewrite yaml  

### ISSUE THREAD

**Issue by Shiva2199** [openrewrite/rewrite-maven-plugin#617]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v1.2.3
- Maven 3.9.x
- rewrite-_module_ v1.2.3

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```xml
<plugin>
  <groupId>org.openrewrite.maven</groupId>
  <artifactId>rewrite-maven-plugin</artifactId>
  <version>1.2.3</version>
  <configuration>
    ... 
  </configuration>
</plugin>
```

## What is the smallest, simplest way to reproduce the problem?

Create custom recipe with .yaml extension (not .yml)

## What did you expect to see?

```
I expect the custom recipe to run with both .yaml and .yml extension as both are the same in interpretation and syntax.
```

## What did you see instead?
 Error

## What is the full stack trace of any errors you encountered?

```
Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:5.4.1:run failed: Recipes not found:
```

**Comment by timtebeek** [comment]
Hi @Shiva2199 ; The name of the custom recipe file is [configurable through a property](https://openrewrite.github.io/rewrite-maven-plugin/run-mojo.html), and by default set to `rewrite.yml`.
https://github.com/openrewrite/rewrite-maven-plugin/blob/88e5c0bb83308473b0a98d09279ecbfdf70077fc/src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java#L40-L41

If you want to use a different filename, such as `rewrite.yaml` or `custom.yaml` then you can override the associated property to set a different path:
```bash
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run \
  -Drewrite.activeRecipes=org.example.Recipe \
  -Drewrite.configLocation=rewrite.yaml
```
Hope that solves your issue!
