### ISSUE TITLE
Parsing events not published for resources parsed with ResourceParser

### ISSUE THREAD

**Issue by fabapp2** [openrewrite/rewrite-maven-plugin#622]
The `ResourceParser` in `main` [creates a new `ExecutionContext`](https://github.com/openrewrite/rewrite-maven-plugin/blob/61b92e4d5580cb57d46cc26c63488b7b33eb3f51/src/main/java/org/openrewrite/maven/ResourceParser.java#L80) and removes all previous settings.
Thus, previously registered `ParsingEventListener`s are not called.

Fix: The parseSourceFiles() method should take the ExecutionContext as parameter

I could provide a PR providing an overloaded `parseSourceFiles()` method that takes an `ExecutionContext` as (temp) fix?

**Comment by timtebeek** [comment]
A quick heads up that we're likely to revisit this soon as we transition to [the OmniParser introduced in rewrite-polyglot](https://github.com/openrewrite/rewrite-polyglot/blob/main/src/main/java/org/openrewrite/polyglot/OmniParser.java). We're revisiting progress indicators for our own CLI as well, which I imagine you should be able to benefit from too. Would you be ok to wait a week or two to see how that pans out?

**Comment by fabapp2** [comment]
Sure. Sounds interesting. I will have a look.

**Comment by timtebeek** [comment]
Where I previously expected the progress bar changes in rewrite-polyglot to make it into rewrite-maven-plugin, we have instead only applied those to the moderne-maven-plugin. As such I don't expect any changes to the rewrite-maven-plugin for progress indications for now that would conflict with any changes made here.

> I could provide a PR providing an overloaded parseSourceFiles() method that takes an ExecutionContext as (temp) fix?

If it helps your case feel free to provide that overload, and be sure to indicate the intended use in a comment or JavaDoc, such that we don't see any inadvertent uncoordinated removal in the future.

Thanks for your patience! With the travel and ongoing work it only now became clear what direction we'd take and what the impact would be.
