### ISSUE TITLE
Cant' exclude dependency-reduced-pom.xml

### ISSUE THREAD

**Issue by philippe-granet** [openrewrite/rewrite-maven-plugin#650]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.8.4
- Maven plugin v5.10.0

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```xml
<plugin>
  <groupId>org.openrewrite.maven</groupId>
  <artifactId>rewrite-maven-plugin</artifactId>
  <version>8.8.4</version>
</plugin>
```

## What is the smallest, simplest way to reproduce the problem?

Use Maven Shade plugin and add `dependency-reduced-pom.xml` to excluded files (`-Drewrite.exclusions=dependency-reduced-pom.xml`)

## What did you expect to see?

No patch generated for dependency-reduced-pom.xml

## What did you see instead?

Patch generated for dependency-reduced-pom.xml

**Comment by Bananeweizen** [comment]
I've also not been able to use exclusions successfully. I have this configuration to match folders like `src-gen` and similar, but generated files are still modified:
```
<exclusions>
	<!-- generated code -->
	<exclusion>**/*-gen/**</exclusion>
</exclusions>
```

**Comment by timtebeek** [comment]
Hmm; the reason for this will be that we ask Maven what files to process, and likely this is one of the files returned.

https://github.com/openrewrite/rewrite-maven-plugin/blob/d1b68cdce46e9dfc2efa6fd133d2873ddf08e8ce/src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java#L150-L153
https://github.com/openrewrite/rewrite-maven-plugin/blob/d1b68cdce46e9dfc2efa6fd133d2873ddf08e8ce/src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java#L463-L467

The Maven shade plugin `dependency-reduced-pom.xml` has bitten me in the past as well, but went away when I added `-DDuseDependencyReducedPomInJar=false`. Does that work for you as well @philippe-granet ?

**Comment by timtebeek** [comment]
Just a quick note here that @rickie has reported seeing the same issue with [ci-friendly-flatten-maven-plugin](https://github.com/outbrain-inc/ci-friendly-flatten-maven-plugin). Any fix ideally takes both into account, to fall back to the original pom.xml, not any modified pom.

**Comment by philippe-granet** [comment]
> The Maven shade plugin `dependency-reduced-pom.xml` has bitten me in the past as well, but went away when I added `-DuseDependencyReducedPomInJar=false`. Does that work for you as well @philippe-granet ?

In my case, developer have commited  `dependency-reduced-pom.xml` ...

I propose this MR to fix the problem: https://github.com/openrewrite/rewrite-maven-plugin/pull/908

**Comment by rickie** [comment]
Thanks @timtebeek for taking that case into account 😄  !
