### ISSUE TITLE
No plugin found for prefix 'rewrite' while trying to upgrade the java 8 to java 17

### ISSUE THREAD

**Issue by kp144** [openrewrite/rewrite-maven-plugin#651]
<plugin>

<groupId>org.openrewrite.maven</groupId>

<artifactId>rewrite-maven-plugin</artifactId>

<version>5.4.1</version>

<configuration>

<activeRecipes>

<recipe>org.openrewrite.java.migrate.Upgrade ToJava17</recipe>

</activeRecipes>

</configuration>

<dependencies>

<dependency>

<groupId>org.openrewrite.recipe</groupId>

<artifactId>rewrite migrate-java</artifactId>

<version>2.0.9</version>

</dependency>

</dependencies>

</plugin>

**Comment by timtebeek** [comment]
It's unclear what you're asking or have tried from just the above. It helps if you add your configuration and the command you used, as per the template here: https://github.com/openrewrite/.github/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

Going off the limited information above it sounds like you did not add `rewrite-maven-plugin` to your `pom.xml` file, and then ran `mvn rewrite:run`. We have a detailed guide available here that goes over the steps in more details: https://docs.openrewrite.org/running-recipes/popular-recipe-guides/migrate-to-java-17

I'll close the issues for now, as it's not clear what can be done. If your problems persist despite following the above instructions then please let us know.

**Comment by kp144** [comment]
<plugin>

<groupId>org.openrewrite.maven</groupId>

<artifactId>rewrite-maven-plugin</artifactId>

<version>5.4.1</version>

<configuration>

<activeRecipes>

<recipe>org.openrewrite.java.migrate.UpgradeToJava17</recipe>

</activeRecipes>

</configuration>

<dependencies>

<dependency>

<groupId>org.openrewrite.recipe</groupId>

<artifactId>rewrite-migrate-java</artifactId>

<version>2.0.9</version>

</dependency>

</dependencies>

</plugin>

I am using this configuration but still getting the same exception which I have mentioned above

**Comment by timtebeek** [comment]
There's still a couple of open questions:
- Is it a single or multi module project?
- Which file did you place the configuration in?
- What command are running & from which folder?
- Is the above snippet in `<build><plugins>...</plugins></build>` and not for instance in `<pluginManagement>` or <profiles>` ?

It really helps us help you if you use to [the issue template](https://github.com/openrewrite/.github/blob/main/.github/ISSUE_TEMPLATE/bug_report.md).
