### ISSUE TITLE
Recipesnot found in multimodule when parent is specified

### ISSUE THREAD

**Issue by lrkwz** [openrewrite/rewrite-maven-plugin#659]
## What version of OpenRewrite are you using?

I am using:

- Maven/Gradle plugin 5.11.0

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a MULTI module project structured as:

```
.
├── A
│   └── pom.xml
├── B
│   └── pom.xml
├── pom.xml
└── rewrite.yml
```

Where ./pom.xml is:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.garanteasy</groupId>
  <artifactId>garanteasy-webapp-packager</artifactId>
  <version>1</version>
  <packaging>pom</packaging>
  <modules>
    <module>A</module>
    <module>B</module>
  </modules>
  <properties>
    <spring-boot.version>2.7.17</spring-boot.version>
  </properties>
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.openrewrite.maven</groupId>
          <artifactId>rewrite-maven-plugin</artifactId>
          <version>5.11.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.openrewrite.maven</groupId>
        <artifactId>rewrite-maven-plugin</artifactId>
        <configuration>
          <activeRecipes>
            <recipe>com.garanteasy.ChangeSpringBootPropertyValue</recipe>
          </activeRecipes>
          <failOnDryRunResults>true</failOnDryRunResults>
          <configLocation>${project.basedir}/rewrite.yml</configLocation>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

rewrite.yml is:

```yml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.garanteasy.ChangeSpringBootPropertyValue
displayName: Change Maven project `spring-boot.version` property value
recipeList:
  - org.openrewrite.maven.ChangePropertyValue:
      key: spring-boot.version
      newValue: 2.7.17
      addIfMissing: false
      trustParent: true
```

A/pom.xml is:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.garanteasy</groupId>
    <artifactId>garanteasy-webapp-packager</artifactId>
    <version>1</version>
    <relativePath>..</relativePath>
  </parent>
  <groupId>com.garanteasy</groupId>
  <artifactId>A</artifactId>
  <properties>
    <spring-boot.version>2.7.17</spring-boot.version>
  </properties>
</project>
```
B/pom.xml is:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.garanteasy</groupId>
    <artifactId>garanteasy-webapp-packager</artifactId>
    <version>1</version>
    <relativePath>..</relativePath>
  </parent>
  <groupId>com.garanteasy</groupId>
  <artifactId>B</artifactId>
</project>
```

## What is the smallest, simplest way to reproduce the problem?

With those files the output of `mvn rewrite:discover` is correct:

```
[INFO] --- rewrite:5.11.0:discover (default-cli) @ garanteasy-webapp-packager ---
[INFO] Available Recipes:
[INFO]     com.garanteasy.ChangeSpringBootPropertyValue
...
[INFO] Active Recipes:
[INFO]     com.garanteasy.ChangeSpringBootPropertyValue
[INFO]
[INFO] Found 228 available recipes and 6 available styles.
[INFO] Configured with 1 active recipes and 0 active styles.
```
BUT `mvn rewrite:run` fails with error:

```
[ERROR] Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:5.11.0:run (default-cli) on project B: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:5.11.0:run failed: Recipesnot found: com.garanteasy.ChangeSpringBootPropertyValue -> [Help 1]
```
## Workaround

As described in [Chapter 6. A Multi-module Project (Maven by Example)](http://books.sonatype.com/mvnex-book/reference/multimodule.html) each sub module defines as the `<parent>` the "aggregator" in the parent directory: **if you remove the parent from modules A and B the receipt is correctly found.**.

## What is the full stack trace of any errors you encountered?

[stacktrace.log](https://github.com/openrewrite/rewrite-maven-plugin/files/13376336/stacktrace.log)

**Comment by lrkwz** [comment]
The problem raises only if the module's parent is the "aggregator". 

Recipes are correctly resolved if there's no parent OR if each module has a parent which is NOT the aggregator pom (i.e. you can declare spring-boot-starter-parent in each module if you wish).

**Comment by timtebeek** [comment]
Just to be clear; from which working directory are you running `rewrite:run` in the above situation? Is it in the individual modules? Or in the parent directory? I'd expect things to only work from the parent directory.

**Comment by lrkwz** [comment]
> Just to be clear; from which working directory are you running `rewrite:run` in the above situation? Is it in the individual modules? Or in the parent directory? I'd expect things to only work from the parent directory.

I run it nly from the parent directory.

**Comment by timtebeek** [comment]
Was able to reproduce your issue here; in short: remove `<configLocation>${project.basedir}/rewrite.yml</configLocation>` and it works again. There's no need to set the configLocation for the default location of rewrite.yml. The default value is `${maven.multiModuleProjectDirectory}/rewrite.yml`, which works in multi module projects like yours. More information about the various configuration options can be found here: https://openrewrite.github.io/rewrite-maven-plugin/run-mojo.html

Hope that helps!

**Comment by lrkwz** [comment]
> Was able to reproduce your issue here; in short: remove `<configLocation>${project.basedir}/rewrite.yml</configLocation>` and it works again. There's no need to set the configLocation for the default location of rewrite.yml. The default value is `${maven.multiModuleProjectDirectory}/rewrite.yml`, which works in multi module projects like yours. More information about the various configuration options can be found here: https://openrewrite.github.io/rewrite-maven-plugin/run-mojo.html
> 

Could be a good idea to document it somewhere.

**Comment by timtebeek** [comment]
> Could be a good idea to document it somewhere.

Any suggestions on where to add documentation? Right now the default value is listed on that [plugin run goal configuration](https://openrewrite.github.io/rewrite-maven-plugin/run-mojo.html). It works if the default value was not explicitly overridden with another value.
