### ISSUE TITLE
Maven plugin should not duplicate work between rewrite:warn and rewrite:fix

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite-maven-plugin#70]
rewrite:warn always runs. rewrite:fix runs when specifically requested. 
Right now they both do all of the parsing and visiting. So any time you run rewrite:fix all of the same work is being done twice since rewrite:warn also runs.

**Comment by jkschneider** [comment]
![image](https://user-images.githubusercontent.com/1697736/101961339-5de44c80-3bbe-11eb-93fc-a19a8c217138.png)

**Comment by sambsnyd** [comment]
We will not be producing any AST jars as part of this plugin. An alternate idea is to have warn produce patch files and fix apply them. Then the work is done only in warn.

**Comment by sambsnyd** [comment]
At some point we fixed this. rewrite:warn doesn't run anymore when you only invoke rewrite:fix
