### ISSUE TITLE
Add exclusions configuration maven as parameter

### ISSUE THREAD

**Issue by sergiogp98** [openrewrite/rewrite-maven-plugin#704]
## What problem are you trying to solve?
I am running recipes using a YAML file and using mvn command directly. However, it takes too long since it analyses files I don't want to.

## Describe the solution you'd like
I would like to have a mvn command parameter to exclude files. For example _mvn -Drewrite.exclusions=folder/**_
 
## Have you considered any alternatives or workarounds?
I have considered adding `<configuration><exclusions>...</exclusions></configuration>`  in pom.xml file but I didn't work

**Comment by timtebeek** [comment]
According to our docs exclusions do have user properties as well:
https://openrewrite.github.io/rewrite-maven-plugin/run-mojo.html

The question then is what values you were using and how. Are you not quoting your value on the commandline for instance?
`-Drewrite.exclusions="folder/**"`

**Comment by sergiogp98** [comment]
Thank you @timtebeek! I was not using quotes.
