### ISSUE TITLE
Maven plugin `5.23.2` fails to run maven recipes.

### ISSUE THREAD

**Issue by caesar-ralf** [openrewrite/rewrite-maven-plugin#745]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.15.2
- Maven plugin v5.23.2
- rewrite-recipe-bom v2.6.4
- OpenJDK Runtime Environment Corretto-21.0.2.13.1 (build 21.0.2+13-LTS)
- Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

## How are you running OpenRewrite?

Any recipe using maven, for example the one to upgrade to Java21:

```bash
mvn -U org.openrewrite.maven:rewrite-maven-plugin:5.23.2:run \
  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-migrate-java:RELEASE \ 
  -Drewrite.activeRecipes=org.openrewrite.java.migrate.UpgradeToJava21
```

## What is the smallest, simplest way to reproduce the problem?

I couldn't find yet a way, but running the same code with maven plugin version `5.23.0` works perfectly.

Problem occurred when running for module `future` from this repo https://github.com/spotify/java-hamcrest/tree/master/future

## What did you see instead?
The following error:

```java
[ERROR] Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:5.23.2:run (default-cli) on project ice-box-checks-status-service: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:5.23.2:run failed: Error while visiting pom.xml: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "groupId" is null
[ERROR]   org.openrewrite.maven.RemoveRedundantDependencyVersions.getManagedPluginVersion(RemoveRedundantDependencyVersions.java:178)
[ERROR]   org.openrewrite.maven.RemoveRedundantDependencyVersions.access$200(RemoveRedundantDependencyVersions.java:35)
[ERROR]   org.openrewrite.maven.RemoveRedundantDependencyVersions$1.matchesVersion(RemoveRedundantDependencyVersions.java:147)
[ERROR]   org.openrewrite.maven.RemoveRedundantDependencyVersions$1.visitTag(RemoveRedundantDependencyVersions.java:104)
[ERROR]   org.openrewrite.maven.RemoveRedundantDependencyVersions$1.visitTag(RemoveRedundantDependencyVersions.java:98)
[ERROR]   org.openrewrite.xml.tree.Xml$Tag.acceptXml(Xml.java:445)
[ERROR]   org.openrewrite.xml.tree.Xml.accept(Xml.java:53)
[ERROR]   org.openrewrite.TreeVisitor.visit(TreeVisitor.java:283)
[ERROR]   org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:366)
[ERROR]   org.openrewrite.xml.XmlVisitor.lambda$visitTag$2(XmlVisitor.java:91)
[ERROR]   org.openrewrite.internal.ListUtils.map(ListUtils.java:176)
[ERROR]   org.openrewrite.xml.XmlVisitor.visitTag(XmlVisitor.java:91)
[ERROR]   org.openrewrite.maven.MavenIsoVisitor.visitTag(MavenIsoVisitor.java:38)
[ERROR]   org.openrewrite.maven.RemoveRedundantDependencyVersions$1.visitTag(RemoveRedundantDependencyVersions.java:118)
[ERROR]   org.openrewrite.maven.RemoveRedundantDependencyVersions$1.visitTag(RemoveRedundantDependencyVersions.java:98)
[ERROR]   org.openrewrite.xml.tree.Xml$Tag.acceptXml(Xml.java:445)
```

## What is the full stack trace of any errors you encountered?

[maven-debug.txt](https://github.com/openrewrite/rewrite-maven-plugin/files/14407237/maven-debug.txt)

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Yeah, I could potentially help.

**Comment by timtebeek** [comment]
Hi! You're quick; thanks for immediately trying out today's new version and reporting the issue here. I think that will be fixed by this change https://github.com/openrewrite/rewrite/commit/4c176e2a3fb3ee4fb7f9ca31fad1208244695dfa, as you likely use an implicit default groupId for a plugin. We'll need to do a new release of openrewrite/rewrite and rewrite-maven-plugin to get this change to you.

Alternatively, you can run [ExplicitPluginGroupId](https://docs.openrewrite.org/recipes/maven/cleanup/explicitplugingroupid), which would add a groupId as seen in the tests here:
https://github.com/openrewrite/rewrite/blob/4a6a157e8cdbc0798449ae896da33c609213394a/rewrite-maven/src/test/java/org/openrewrite/maven/cleanup/ExplicitPluginGroupIdTest.java#L28-L78

**Comment by timtebeek** [comment]
Ok I've [released openrewrite/rewrite 8.18.1](https://github.com/openrewrite/rewrite/releases/tag/v8.18.1) already; would you mind giving the [plugin snapshot version](https://docs.openrewrite.org/reference/snapshot-instructions) a go?
After: https://github.com/openrewrite/rewrite-maven-plugin/actions/runs/8054568902/job/21999420197

**Comment by caesar-ralf** [comment]
> https://github.com/openrewrite/rewrite-maven-plugin/actions/runs/8054568902/job/21999420197

it was more me not defining the version and maven picking up the latest one :P

Anyway, tested it out and same problem occurred. Here is the full debug log:
[debug.txt](https://github.com/openrewrite/rewrite-maven-plugin/files/14416373/debug.txt)

**Comment by timtebeek** [comment]
Thanks for the quick reply; new attempt then which should really be null safe:
https://github.com/openrewrite/rewrite/commit/78bbc098432dfc1f8a249b8f2c5deb40fa19ffc8

**Comment by caesar-ralf** [comment]
That worked @timtebeek, but I wonder if that won't just cause problem as there's plugins where groupId is implied (namely, the maven default group ids)?

**Comment by timtebeek** [comment]
So just to be sure, would you then advocate to go for something like the following?
```diff
diff --git a/rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java b/rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java
index 8dd4b9806..911dbbaf2 100644
--- a/rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java
+++ b/rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java
@@ -28,6 +28,7 @@
 
 import java.util.List;
 import java.util.Objects;
+import java.util.Optional;
 
 import static org.openrewrite.internal.StringUtils.matchesGlob;
 
@@ -176,7 +177,9 @@ && matchesGlob(d.getArtifactId(), exceptedArtifactId)) {
     @Nullable
     private static String getManagedPluginVersion(ResolvedPom resolvedPom, @Nullable String groupId, String artifactId) {
         for (Plugin p : resolvedPom.getPluginManagement()) {
-            if (Objects.equals(p.getGroupId(), groupId) &&
+            if (Objects.equals(
+                    Optional.ofNullable(p.getGroupId()).orElse("org.apache.maven.plugins"),
+                    Optional.ofNullable(groupId).orElse("org.apache.maven.plugins")) &&
                 Objects.equals(p.getArtifactId(), artifactId)) {
                 return resolvedPom.getValue(p.getVersion());
             }
```

Or did you have something else in mind still?

**Comment by caesar-ralf** [comment]
> So just to be sure, would you then advocate to go for something like the following?
> 
> ```diff
> diff --git a/rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java b/rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java
> index 8dd4b9806..911dbbaf2 100644
> --- a/rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java
> +++ b/rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java
> @@ -28,6 +28,7 @@
>  
>  import java.util.List;
>  import java.util.Objects;
> +import java.util.Optional;
>  
>  import static org.openrewrite.internal.StringUtils.matchesGlob;
>  
> @@ -176,7 +177,9 @@ && matchesGlob(d.getArtifactId(), exceptedArtifactId)) {
>      @Nullable
>      private static String getManagedPluginVersion(ResolvedPom resolvedPom, @Nullable String groupId, String artifactId) {
>          for (Plugin p : resolvedPom.getPluginManagement()) {
> -            if (Objects.equals(p.getGroupId(), groupId) &&
> +            if (Objects.equals(
> +                    Optional.ofNullable(p.getGroupId()).orElse("org.apache.maven.plugins"),
> +                    Optional.ofNullable(groupId).orElse("org.apache.maven.plugins")) &&
>                  Objects.equals(p.getArtifactId(), artifactId)) {
>                  return resolvedPom.getValue(p.getVersion());
>              }
> ```
> 
> Or did you have something else in mind still?

Yeah, I think that might work as the artifact id still needs to match 👍 thanks @timtebeek

**Comment by codefromthecrypt** [comment]
what's the easiest way to use this snapshot in rewrite-maven-plugin? because I just ran into this today..

**Comment by timtebeek** [comment]
We needed one more follow up commit to now guard against empty plugin blocks https://github.com/openrewrite/rewrite/commit/e2a8cb87cee13ab0be38d55815999fbc76a42bd7

We've [documented the flow for snaphot versions](https://docs.openrewrite.org/reference/snapshot-instructions), which in this case comes down to adding `https://oss.sonatype.org/content/repositories/snapshots` as a `<pluginRepository>` and using `5.24.0-SNAPSHOT`.

But since this is starting to affect more folks, I think it's easiest that I just push out a new path release of the plugin to get you all unblocked. I hope to have `5.23.3` released and available in the next half an hour or so.

**Comment by codefromthecrypt** [comment]
In hindsight my question was lazy and even if you didn't document, I could have guessed ;) Thanks for your patience with me. Looking forward to 5.23.3!

**Comment by timtebeek** [comment]
No worries at all; glad to see you're still using the tools over there! Let me know if there's every anything to collaborate on. :)

**Comment by codefromthecrypt** [comment]
yep k8s java client needs a lot of migration help, so added first PR towards that https://github.com/kubernetes-client/java/pull/3125
