### ISSUE TITLE
Sum and show time saved from running recipes, similar to Gradle plugin

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-maven-plugin#781]
## What problem are you trying to solve?
Show folks how much time is estimated to be saved through running recipes, to show appreciation to recipe authors and encourage more use.

## Describe the solution you'd like
The same as was done for the Gradle plugin, but now applied to the Maven plugin
- https://github.com/openrewrite/rewrite-gradle-plugin/pull/294

**Comment by nicolasb29** [comment]
I have created a pull request #782. Can you check because I never use Maven.
