### ISSUE TITLE
Running rewrite rules gets errors in other goals if run with java 17

### ISSUE THREAD

**Issue by davidmichaelkarr** [openrewrite/rewrite-maven-plugin#825]
I am working on a process that developers on related teams can use to convert their codebases from using Java 11 and SpringBoot 2.x to Java 17 and SpringBoot 3.x.  We are trying to use openrewrite rules to convert swagger to openapi, and also to convert javax to jakarta.

Some other developers on my "platform" team assembled the following command line to do the first conversion:

```
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-spring:RELEASE -Drewrite.activeRecipes=org.openrewrite.openapi.swagger.SwaggerToOpenAPI,org.openrewrite.openapi.swagger.MigrateApiModelPropertyToSchema
```

What we find is that besides running this "run" goal, it also executes other plugins defined in the pom.xml. For instance, the build I'm testing this on uses the "org.jvnet.jaxb2.maven2:maven-jaxb2-plugin" plugin.  As part of the upgrade process, we have to convert this to a different plugin, but that's defined in a later step, after we execute these openrewrite rules.

When I run this with Java 11, it does successfully execute the openrewrite rule, but it does also execute that other goal, including "compile" and "testCompile". When we run this with Java 17, we get errors with the "jaxb2" plugin, because that plugin can't be used with Java 17.  If we absolutely had to, we could specify in the upgrade process that you can't install Java 17 until you complete the openrewrite rules, but that's a little awkward.  Is there some way we can configure this mvn command line so that it can work with Java 17 by ONLY executing the openrewrite rules, and is it possible for the rules to succeed that way?

**Comment by timtebeek** [comment]
Hi @davidmichaelkarr ; Good to hear you're exploring recipes to help you modernize your applications. 

To run recipes we first need to build up a detailed model of your code, which we then manipulate with recipes before writing the changes back out to disk. As part of building up the model we ask Maven to run the lifecycle goals up until `proces-test-classes`, as that's what[ our RewriteRunMojo](https://github.com/openrewrite/rewrite-maven-plugin/blob/730313d735e84053a32f692b425c409ecdd3f68b/src/main/java/org/openrewrite/maven/RewriteRunMojo.java#L29-L32) needs to be able to use any generated classes for type attribution.

It sounds like you're finding you can only run subsequent recipes on Java 17 once the jaxb2 plugin is converted, as that fails to work on Java 17. I'm looking through the likely version of that plugin you're using ([v0.15.3](https://github.com/highsource/jaxb-tools/tree/0.15.3)) to see if there's a way to skip that particular plugin, but there does not appear to be such an option.

What might then help is to automate the code changes you need to do to move away from `maven-jaxb2-plugin` as a recipe, and include that with the recipes you run from Java 11. That's the typical flow we have for composing recipes together, either through a `rewrite.yml` file, or by setting multiple active recipes as you're already doing. For help with recipe development feel free to join [our Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA).

I hope that helps provide you with the context, even if we don't immediately have a way to disable that troublesome `maven-jaxb2-plugin` on Java 17 just yet.

**Comment by timtebeek** [comment]
There is one alternative that I can offer, which is [the Moderne CLI](https://docs.moderne.io/user-documentation/moderne-cli/getting-started/cli-intro); that's a tool we've developed at Moderne to run those same OpenRewrite recipes conveniently at scale across repositories. That discovers the Java versions installed on a system, as well as what's required per project, and then runs the recipes using the appropriate Java version for that project, such that users don't have to wrestle with selecting the right Java version. The CLI is meant to speed up precisely these types of migrations, and other uses, developed by the same team. If you'd like to try that out you can [fill out this form](https://www.moderne.ai/moderne-ide-plugin-signup).

**Comment by timtebeek** [comment]
Reading over this issue again perhaps the `-NoFork` goals can be of some help here, as those might stop your build from running other goals like the jaxb2 plugin you mentioned: https://openrewrite.github.io/rewrite-maven-plugin/runNoFork-mojo.html

I hope that's of some use to you there still; beyond that I don't think there's much we can do for this issue apart from the options outlined above. As such I'll close this issue for now, but happy to continue the conversation either here, or in [our Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA). Wishing you all the best!
