### ISSUE TITLE
Evaluate cutting releases off git tags pushed to remote

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite-maven-plugin#83]
conceptual follow-up to https://github.com/openrewrite/rewrite-maven-plugin/issues/79

In order to have `rewrite-maven-plugin` use the same release process flow as other `openrewrite` projects, evaluate enabling cutting releases of this project by first `git tag`ing a commit with the desired release tag, _then_ pushing the tag to remote, and having the release engineering workflow publish the release off the tag.

## further context

This in contrast to the current process of taking whatever the current latest HEAD commit is, initiating a release, and having that commit be the new version to use (which also isn't particularly robust since it only bumps patch versions right now). See this comment specifically (https://github.com/openrewrite/rewrite-maven-plugin/issues/79#issuecomment-765001308).

This is a little trickier than it may initially seem, since the `<version>...</>` would need to be dynamically passed in to the `pom.xml` (could be done as a property via `<version>${revision}</version>`, but that might also fight with how the `maven-release-plugin` works. Then again, in this model, it could just as well be that the `maven-release-plugin` be removed entirely in favor of performing `./mvnw deploy -Drevision=${some-git-tag}` or something. (I don't know, just externalizing the thought 👍 )

**Comment by sambsnyd** [comment]
While I do want this, indeed I specifically asked for this, the current release process works well so this isn't worth the trouble for the foreseeable future.
