### ISSUE TITLE
rewrite-maven-plugin no longer compatible with Java 17

### ISSUE THREAD

**Issue by motlin** [openrewrite/rewrite-maven-plugin#834]
Dependabot opened [a PR against my project](https://github.com/liftwizard/liftwizard/pull/2284) bumping org.openrewrite.maven:rewrite-maven-plugin from 5.37.1 to 5.38.0.

My project has a GitHub workflow configured to run dryRunNoFork, which fails with the error:

`org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:5.38.0:dryRunNoFork (OpenRewrite dry run) on project liftwizard-parent-build: The plugin org.openrewrite.maven:rewrite-maven-plugin:5.38.0 has unmet prerequisites: Required Java version 21 is not met by current version: 17.0.10`

Looking at the diffs in https://github.com/openrewrite/rewrite-maven-plugin/compare/v5.37.1...v5.38.0, I see that rewrite-java-21 was added, but that source and target version numbers were not bumped, so I believe this incompatibility is unintentional.

**Comment by timtebeek** [comment]
Apologies! That's quite unexpected; I've reverted that change for now and will make it into the next release. We'll have to revisit this more carefully in the near future.

**Comment by motlin** [comment]
This issue is reoccurring now that https://github.com/openrewrite/rewrite-maven-plugin/pull/872 is released.

**Comment by timtebeek** [comment]
Thanks for the quick feedback @motlin ! I think we have a structural fix now, whereas before we were relying on an automatically detected required Java version. I've ran a local snapshot against `liftwizard` using Java 17 and no longer see any issues, so thanks for providing that context above! 🙏🏻 

Also be sure to let us know if you develop any Dropwizard related recipes, or would like to collaborate on some. I imagine there's some potential for migration recipes there as well, and happy to accommodate with say a rewrite-dropwizard module.

**Comment by motlin** [comment]
> Also be sure to let us know if you develop any Dropwizard related recipes, or would like to collaborate on some. I imagine there's some potential for migration recipes there as well, and happy to accommodate with say a rewrite-dropwizard module.

That is a great idea. We're stuck on Dropwizard 2.x at my work, and so I've stayed with the same dependency in Liftwizard. The Dropwizard 3.x upgrade involves [package moves](https://www.dropwizard.io/en/stable/manual/upgrade-notes/upgrade-notes-3_0_x.html#dropwizard-package-structure-and-jpms) that OpenRewrite would be perfect for. The Dropwizard 4.x upgrade involves [moving from javax to jakarta](https://www.dropwizard.io/en/stable/manual/upgrade-notes/upgrade-notes-4_0_x.html), which looks like it's completely covered by [an existing recipe](https://docs.openrewrite.org/recipes/java/migrate/jakarta/javaxmigrationtojakarta).

I'll talk to coworkers about attempting the Dropwizard 3.x upgrade in the near future using OpenRewrite and working in the open.

**Comment by motlin** [comment]
> the Change package for Dropwizard

Is there a recipe like org.openrewrite.java.ChangePackage to split up a package? The package io.dropwizard got split up into several packages. I think I'll need to list a bunch of fully qualified class names.

**Comment by timtebeek** [comment]
> > the Change package for Dropwizard
> 
> Is there a recipe like org.openrewrite.java.ChangePackage to split up a package? The package io.dropwizard got split up into several packages. I think I'll need to list a bunch of fully qualified class names.

You can use `ChangePackage` and `ChangeType` together, even if the intermediate result would not be valid. That way you can "move" everything over to the new package, and then "move" some of the classes to the other part of the split package. I hope that's clear; Feel free to when you want to start a module and work from the tests there. :)
