### ISSUE TITLE
5.44.0 Breaking change: AddDependency onlyIfUsing not working for pom

### ISSUE THREAD

**Issue by davidh44** [openrewrite/rewrite-maven-plugin#894]
## What version of OpenRewrite are you using?

OpenRewrite 5.44.0

## How are you running OpenRewrite?

Running `mvn org.openrewrite.maven:rewrite-maven-plugin:run` in unit test

https://github.com/aws/aws-sdk-java-v2/blob/master/test/v2-migration-tests/src/test/java/software/amazon/awssdk/v2migrationtests/MavenProjectTest.java#L81

Pinning to 5.43.0 works.

## Errors

The apache-client and netty-nio-client dependencies are no longer added to the pom.xml by this recipe 

https://github.com/aws/aws-sdk-java-v2/blob/master/v2-migration/src/main/resources/META-INF/rewrite/upgrade-sdk-dependencies.yml#L22-L30

Expected missing transformation (works with pinned previous versions)

https://github.com/aws/aws-sdk-java-v2/blob/master/test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/pom.xml#L51-L58

AddDependency still executes correctly on the java classes. ChangeDependency still executes correctly on the pom

**Comment by timtebeek** [comment]
hi @davidh44 ; Sorry to hear about your troubles! We'll do a full new release tomorrow to flush out any such incompatibilities, after which you can update everything to the latest versions and it should all work again.

We had some problems doing a release last week, so we only got halfway, which is why you're seeing these issues now unfortunately. Typically any releases announced together here should all work together: https://github.com/openrewrite/rewrite-recipe-bom/releases

**Comment by timtebeek** [comment]
Hi @davidh44 ! The new release is now available: 
https://github.com/openrewrite/rewrite-recipe-bom/releases/tag/v2.22.0

All the best!

**Comment by davidh44** [comment]
Hmm I'm still seeing the same issue, running 5.45.0, are there any tests covering AddDependency onlyIfUsing transforming pom.xml?

**Comment by timtebeek** [comment]
Did you upgrade both the plugin and the rewrite-recipe-bom version? As I see [the rewrite-recipe-bom is still on 2.17.0](https://github.com/aws/aws-sdk-java-v2/blob/0ce7d42d2403a7cfe4b95b852164a839dc90d66e/v2-migration/pom.xml#L37) in `aws-sdk-java-v2/blob/master/v2-migration/pom.xml`, whereas the latest is https://github.com/openrewrite/rewrite-recipe-bom/releases/tag/v2.22.0

**Comment by davidh44** [comment]
Okay that did the trick, thanks for the catch!
